import type { AiPouls, Onboarding, OnboardingAbandons, Pouls, Services, NotifsEfficacite, ViewMap, ViewName } from "../views";
export type Insight = {text:string; source:string; window:string; tone?:"calme"|"alerte"|"critique"};
export const number = (n:number, digits=1)=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:digits}).format(n);
export const sum = <T>(rows:T[],key:keyof T)=>rows.reduce((n,r)=>n+(typeof r[key]==="number"?Number(r[key]):0),0);
export const percent = (n:number,d:number)=>d>0?100*n/d:null;
export const ratio = (n:number,d:number)=>d>0?`${number(100*n/d)} %`:"taux non calculable";
export const missing = (source:string,window:string,text="Pas encore assez de données pour établir ce constat."):Insight=>({text,source,window});
export function inDays<T extends {jour:string}>(rows:T[],end:string,n:number,offset=0):T[]{const endMs=Date.parse(end+"T00:00:00Z")-offset*86400000;return rows.filter(r=>{const t=Date.parse(r.jour.slice(0,10)+"T00:00:00Z");return t<=endMs&&t>endMs-n*86400000;});}
export function group<T>(rows:T[],label:keyof T,value:keyof T){const map=new Map<string,number>();for(const r of rows){const key=String(r[label]??"Non renseigné");map.set(key,(map.get(key)??0)+(typeof r[value]==="number"?Number(r[value]):0));}return [...map].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value||a.label.localeCompare(b.label));}
export function funnel(rows:Onboarding[]){const keys=["arrivees","confidentialite","service_choisi","connexion_envoyee","compte_ajoute"] as const;const names=["Arrivées","Confidentialité","Service choisi","Connexion envoyée","Compte ajouté"];return keys.map((k,i)=>{const count=sum(rows,k),previous=i?sum(rows,keys[i-1]):count;return {label:names[i],value:count,lost:previous-count,lossPct:i?percent(previous-count,previous):0};});}
export function onboardingInsights(rows:Onboarding[],abandons:OnboardingAbandons[]):Insight[]{
 const source="v_onboarding",window="30 jours, cohortes d’arrivée";
 if(!rows.length)return [missing(source,window),missing("v_onboarding_abandons","30 jours")];
 const steps=funnel(rows),first=steps[0].value,last=steps[4].value,worst=[...steps.slice(1)].sort((a,b)=>b.lost-a.lost)[0];
 const abandon=group(abandons.filter(r=>!r.derniere_etape.startsWith("8.")),"derniere_etape","installs")[0];
 return [{text:`${first-last} installations sur ${first} n’ont pas ajouté de compte. La plus grande perte est avant « ${worst.label} » : ${worst.lost} installations (${ratio(worst.lost,steps[steps.indexOf(worst)-1]?.value??0)}).`,source,window,tone:worst.lost>0?"alerte":"calme"},abandon?{text:`« ${abandon.label} » est la dernière étape la plus fréquente parmi les abandons : ${abandon.value} installations sur ${sum(abandons.filter(r=>!r.derniere_etape.startsWith("8.")),"installs")}.`,source:"v_onboarding_abandons",window:"30 jours"}:missing("v_onboarding_abandons","30 jours")];
}
export function pulseInsights(p?:Pouls):Insight[]{return p?[{text:`${p.north_star_3j} élèves ont travaillé au moins 3 jours sur 7, soit ${number(p.north_star_pct)} % des ${p.actifs_7j} actifs de la semaine.`,source:"v_pouls",window:"7 jours"},{text:`${p.actifs_aujourdhui} élèves actifs aujourd’hui sur ${p.actifs_30j} ce mois-ci : ${number(p.dau_mau_pct)} %, pour un objectif supérieur à 30 %.`,source:"v_pouls",window:"Aujourd’hui / 30 jours",tone:p.dau_mau_pct>30?"calme":"alerte"}]:[missing("v_pouls","7 jours"),missing("v_pouls","Aujourd’hui / 30 jours")];}
export function aiInsights(rows:AiPouls[],p:Pouls|undefined,end:string):Insight[]{const week=inDays(rows,end,7);if(!week.length)return [missing("v_ai_pouls","7 jours"),missing("v_ai_pouls","7 jours","Pannes et refus attendus : données indisponibles.")];const cost=sum(week,"cout_usd_estime"),fails=sum(week,"echecs"),refus=sum(week,"refus");return [{text:`Le moteur IA a coûté ${number(cost,4)} $ sur 7 jours${p&&p.actifs_7j>0?`, soit ${number(cost/p.actifs_7j,4)} $ par élève actif`:". Le nombre d’élèves actifs sur 7 jours manque pour calculer le coût par élève"}.`,source:"v_ai_pouls / v_pouls",window:"7 jours"},{text:`${fails} pannes sur ${sum(week,"requetes")} requêtes, et ${refus} refus attendus (contexte, quota ou débit).`,source:"v_ai_pouls",window:"7 jours",tone:fails?"critique":"calme"}];}
export function serviceInsights(rows:Services[]):Insight[]{const worst=[...rows].sort((a,b)=>b.echec_pct_7j-a.echec_pct_7j)[0];return worst?[{text:`${worst.service} a le taux d’échec le plus élevé : ${number(worst.echec_pct_7j)} % (${worst.syncs_ko_7j} sur ${worst.syncs_ok_7j+worst.syncs_ko_7j} synchronisations). Motif principal : ${worst.motif_principal||"non renseigné"}.`,source:"v_services",window:"7 jours",tone:worst.echec_pct_7j>=20?"critique":worst.echec_pct_7j>=5?"alerte":"calme"},{text:`${rows.filter(r=>r.echec_pct_7j>=5).length} services sur ${rows.length} dépassent ou atteignent le seuil de surveillance de 5 %.`,source:"v_services",window:"7 jours"}]:[missing("v_services","7 jours"),missing("v_services","7 jours","Les taux d’échec par service ne sont pas encore disponibles.")];}
export function notificationInsight(rows:NotifsEfficacite[]):Insight{const map=new Map<string,{sent:number;open:number}>();for(const r of rows){const hour=String(r.heure_prevue).split(":")[0].padStart(2,"0");const v=map.get(hour)??{sent:0,open:0};v.sent+=r.planifiees;v.open+=r.ouvertes;map.set(hour,v);}const sorted=[...map].filter(([,r])=>r.sent>0).sort((a,b)=>b[1].open/b[1].sent-a[1].open/a[1].sent);if(sorted.length<2)return missing("v_notifs_efficacite","Fenêtre fournie par la vue","Deux horaires avec des notifications planifiées sont nécessaires pour comparer les ouvertures.");const [h,a]=sorted[0],[l,b]=sorted[sorted.length-1];return {text:`Les rappels de ${Number(h)} h sont ouverts à ${ratio(a.open,a.sent)} (${a.open}/${a.sent}), contre ${ratio(b.open,b.sent)} à ${Number(l)} h (${b.open}/${b.sent}). Cette comparaison ne prouve pas un effet de l’horaire.`,source:"v_notifs_efficacite",window:"Fenêtre fournie par la vue"};}
export type Dataset = {[K in ViewName]?:ViewMap[K][]};
export function pageInsights(page:string,d:Dataset,end:string):Insight[]{
 if(page==="entonnoir")return onboardingInsights(d.v_onboarding??[],d.v_onboarding_abandons??[]);
 if(page==="services")return serviceInsights(d.v_services??[]);
 if(page==="ia")return [...aiInsights(d.v_ai_pouls??[],d.v_pouls?.[0],end),missing("v_ai_rebond","Fenêtre fournie par la vue","Le rebond après un refus reste non interprétable sans trafic réel.")];
 if(page==="retention") {const rows=[...(d.v_retention??[])].filter(r=>r.j7_pct!==null).sort((a,b)=>b.cohorte.localeCompare(a.cohorte));return [rows[0]?{text:`La cohorte du ${rows[0].cohorte} réunit ${rows[0].eleves} élèves ; ${number(rows[0].j7_pct!)} % reviennent à J7${rows[1]?`, contre ${number(rows[1].j7_pct!)} % pour la cohorte du ${rows[1].cohorte}`:". Une autre cohorte mature manque pour comparer"}.`,source:"v_retention",window:"Cohortes avec J7 mesuré"}:missing("v_retention","Cohortes"),...(d.v_ecrans?.length?[{text:`${group(d.v_ecrans,"ecran","vues")[0].label} arrive en tête avec ${group(d.v_ecrans,"ecran","vues")[0].value} vues sur ${sum(d.v_ecrans,"vues")}.`,source:"v_ecrans",window:"7 jours"}]:[missing("v_ecrans","7 jours")])];}
 if(page==="rituel"){const rows=d.v_gamification??[],week=inDays(rows,end,7),before=inDays(rows,end,7,7);return [week.length?{text:`${sum(week,"journees_validees")} journées validées sur 7 jours${before.length===7&&week.length===7?`, contre ${sum(before,"journees_validees")} les 7 jours précédents`:". Pas encore assez de données pour comparer à la semaine précédente"}.`,source:"v_gamification",window:"7 jours / 7 jours précédents, démo et dev inclus"}:missing("v_gamification","7 jours"),notificationInsight(d.v_notifs_efficacite??[])];}
 if(page==="banque"){const rows=d.v_ai_bank_health??[],aliases=d.v_ai_themes??[];return [rows.length?{text:`${rows.filter(r=>r.published).length} contenus publiés sur ${rows.length} en banque ; ${rows.filter(r=>r.signalements>0).length} ont reçu un signalement.`,source:"v_ai_bank_health",window:"État actuel"}:missing("v_ai_bank_health","État actuel"),aliases.length?{text:`Alias inconnus de la banque : ${aliases.filter(r=>!r.connu_en_banque).length} sur ${aliases.length}. Ils passent en tête de la file de révision.`,source:"v_ai_themes",window:"Fenêtre fournie par la vue"}:missing("v_ai_themes","Fenêtre fournie par la vue")];}
 if(page==="erreurs"){const crash=d.v_crashs??[],sante=d.v_sante_instrumentation??[];return [crash.length?{text:`${sum(crash,"n")} crashs ou rejets sur 14 jours, dont ${sum(crash.filter(r=>r.gravite==="fatal"),"n")} fatals. Les fins brutales sont comptées séparément.`,source:"v_crashs",window:"14 jours, démo et dev inclus",tone:"alerte"}:missing("v_crashs","14 jours","Aucun crash retourné. Consulter la santé de l’instrumentation avant de conclure à l’absence de panne."),sante.length?{text:`Événements jamais vus par l’instrumentation : ${sante.filter(r=>r.etat==="jamais vu").length} sur ${sante.length}.`,source:"v_sante_instrumentation",window:"14 jours"}:missing("v_sante_instrumentation","14 jours")];}
 return [missing("Vues de la page","État actuel"),missing("Vues de la page","État actuel","La comparaison nécessite davantage de données.")];
}
