import type { Config, Banner, ViewResult, FeedbackSupport, Profile, DailyXp, ProfileDetail, PupilBadge, Friendship } from "../views";
import type { geography } from "./geography";
import type { networkStats, NetworkData } from "./network";
import { number, sum, type Insight } from "./index";
import type { AdminPost, AudienceCount } from "@/lib/courrier/model";

export function courrierInsights(posts:AdminPost[], reach:AudienceCount|null, error:boolean):Insight[] {
  const published=posts.filter(p=>p.status==="published"), drafts=posts.filter(p=>p.status==="draft"), notified=published.filter(p=>p.push_sent_at);
  const last=[...published].sort((a,b)=>b.publish_at.localeCompare(a.publish_at))[0];
  const reads=sum(published,"reads");
  return [
    {text:error||!reach?"Les effectifs n'ont pas répondu : impossible de dire qui recevrait un envoi.":`${reach.eleves} élèves ont l'app ; ${reach.joignables} ont un appareil enregistré et recevraient une notification (${reach.eleves-reach.joignables} la liraient seulement en ouvrant la messagerie).`,source:"lucid_admin_audience_count",window:"État actuel",tone:!error&&reach&&reach.joignables<reach.eleves/2?"alerte":"calme"},
    {text:error?"Les envois n'ont pas répondu.":published.length===0?`Aucun envoi publié pour l'instant${drafts.length?`, ${drafts.length} brouillon${drafts.length>1?"s":""} en attente`:""}.`:`${published.length} envoi${published.length>1?"s":""} publié${published.length>1?"s":""}, ${notified.length} avec notification, ${reads} lecture${reads>1?"s":""} en tout. Dernier : « ${last?.title} », ${last?.reads??0} lecture${(last?.reads??0)>1?"s":""}${last?.kind==="poll"?`, ${last.voters} votant${last.voters>1?"s":""}`:""}, ${last?.replies??0} réponse${(last?.replies??0)>1?"s":""}.`,source:"lucid_admin_posts",window:"100 derniers envois"},
  ];
}

export function configurationInsights(config:Config[], banners:Banner[], error:boolean, bannerError:boolean):Insight[] {return [{text:error?"La configuration n’a pas répondu.":`${config.length} clés de configuration chargées. Maintenance : ${config.find(c=>c.key==="maintenance_mode")?.value==="true"?`active pour les versions jusqu’à ${config.find(c=>c.key==="maintenance_max_version")?.value??"toutes"} (les plus récentes passent)`:config.find(c=>c.key==="maintenance_mode")?.value==="false"?"inactive":"non renseignée"}.`,source:"app_config",window:"État actuel"},{text:bannerError?"Les bandeaux n’ont pas répondu.":`Bandeaux actifs : ${banners.filter(b=>b.active).length} sur ${banners.length} affichés.`,source:"app_banners",window:"50 premiers bandeaux"}];}

export function supportInsights(feedback:ViewResult<FeedbackSupport>):Insight[] {return [{text:feedback.error?"Le support n’a pas répondu.":`Retours reçus : ${feedback.data.length}, dont ${feedback.data.filter(r=>r.was_online===false).length} hors connexion.`,source:"v_feedbacks_support",window:"100 derniers retours"},{text:feedback.error?"Les versions concernées ne sont pas connues.":`Versions représentées dans les retours : ${new Set(feedback.data.map(r=>r.app_version)).size}. Aucun volume d’utilisateurs par version ne permet ici de comparer les taux de problème.`,source:"v_feedbacks_support",window:"100 derniers retours"}];}

export function geographyInsights(profiles:ViewResult<Profile>, geo:ReturnType<typeof geography>):Insight[] {const ambigus=geo.schools.filter(s=>s.raison==="ambigu"),sansNom=geo.schools.find(s=>s.raison==="non renseigné");return [{text:profiles.error?"Les profils n’ont pas répondu : les effectifs ne sont pas connus.":`${geo.total-geo.unlocated.length} élèves sur ${geo.total} sont localisés, dont ${geo.precise} par l’annuaire officiel (commune et coordonnées connues) ; ${geo.unlocated.length} restent non localisés.`,source:"profiles.school_name · annuaire",window:"État actuel, comptes de test exclus",tone:geo.unlocated.length>geo.total/2?"alerte":"calme"},{text:profiles.error?"La répartition des établissements reste indisponible.":`${geo.schools.length} établissements ou libellés recensés. ${ambigus.length?`${ambigus.length} noms sont portés par plusieurs villes (${ambigus.reduce((n,s)=>n+s.count,0)} élèves) : à trancher dans data/rattachements-manuels.json.`:"Aucun homonyme à trancher."}${sansNom?` ${sansNom.count} élèves n’ont pas d’établissement renseigné par leur ENT.`:""}`,source:"profiles",window:"État actuel"}];}

export function networkInsights(error:boolean, stats:ReturnType<typeof networkStats>, data:NetworkData):Insight[] {return [{text:error?"La lecture du réseau est incomplète. Impossible de compter les élèves reliés.":`Sur ${stats.total} élèves, ${stats.connected} ont au moins un ami et ${stats.isolated} sont isolés. Le plus grand groupe en relie ${stats.largest}.`,source:"friendships / profiles / profiles_public",window:"État actuel, comptes de test exclus"},{text:error?"Les groupes et le degré moyen restent indisponibles.":`${stats.groups} groupes d’au moins deux élèves ; ${data.links.length} liens uniques, soit ${number(stats.average,2)} amis par élève en moyenne, isolés inclus.`,source:"friendships / profiles",window:"État actuel, amitiés acceptées"}];}

export function pupilInsights(xp:ViewResult<DailyXp>, profile:ViewResult<ProfileDetail>, p:ProfileDetail|undefined, badges:ViewResult<PupilBadge>, friends:ViewResult<Friendship>, id:string):Insight[] {return [{text:xp.error?"L’historique XP n’a pas répondu.":`${sum(xp.data,"amount")} XP sur ${xp.data.length} jours renseignés dans les 30 derniers relevés.`,source:"daily_xp",window:"30 derniers jours renseignés"},{text:profile.error?"Le profil n’a pas répondu.":`Série actuelle : ${p?.streak??0} jours. ${badges.error?"Badges indisponibles.":`Badges acquis : ${badges.data.length}.`} ${friends.error?"Amitiés indisponibles.":`${new Set(friends.data.map(f=>f.user_id===id?f.friend_id:f.user_id)).size} amis acceptés.`}`,source:"profiles / user_badges / friendships",window:"État actuel"}];}
