import type { Post, Config, Banner, ViewResult, FeedbackSupport, Profile, DailyXp, ProfileDetail, PupilBadge, Friendship } from "../views";
import type { geography } from "./geography";
import type { networkStats, NetworkData } from "./network";
import { number, sum, type Insight } from "./index";

export function courrierInsights(posts:Post[], error:boolean):Insight[] {return [{text:error?"Les courriers n’ont pas répondu.":`Brouillons : ${posts.filter(p=>p.status==="draft").length} sur ${posts.length} courriers affichés.`,source:"lucid_posts",window:"50 derniers courriers"},{text:error?"Les états d’envoi sont indisponibles.":`${posts.filter(p=>p.push_sent_at).length} courriers affichés portent une date d’envoi push. L’envoi se fait depuis l’app.`,source:"lucid_posts.push_sent_at",window:"50 derniers courriers"}];}

export function configurationInsights(config:Config[], banners:Banner[], error:boolean, bannerError:boolean):Insight[] {return [{text:error?"La configuration n’a pas répondu.":`${config.length} clés de configuration chargées. Maintenance : ${config.find(c=>c.key==="maintenance_mode")?.value==="true"?"active":config.find(c=>c.key==="maintenance_mode")?.value==="false"?"inactive":"non renseignée"}.`,source:"app_config",window:"État actuel"},{text:bannerError?"Les bandeaux n’ont pas répondu.":`Bandeaux actifs : ${banners.filter(b=>b.active).length} sur ${banners.length} affichés.`,source:"app_banners",window:"50 premiers bandeaux"}];}

export function supportInsights(feedback:ViewResult<FeedbackSupport>):Insight[] {return [{text:feedback.error?"Le support n’a pas répondu.":`Retours reçus : ${feedback.data.length}, dont ${feedback.data.filter(r=>r.was_online===false).length} hors connexion.`,source:"v_feedbacks_support",window:"100 derniers retours"},{text:feedback.error?"Les versions concernées ne sont pas connues.":`Versions représentées dans les retours : ${new Set(feedback.data.map(r=>r.app_version)).size}. Aucun volume d’utilisateurs par version ne permet ici de comparer les taux de problème.`,source:"v_feedbacks_support",window:"100 derniers retours"}];}

export function geographyInsights(profiles:ViewResult<Profile>, geo:ReturnType<typeof geography>):Insight[] {return [{text:profiles.error?"Les profils n’ont pas répondu : les effectifs ne sont pas connus.":`${geo.total-geo.unlocated.length} élèves sur ${geo.total} sont rattachés à une région estimée ; ${geo.unlocated.length} restent non localisés.`,source:"profiles.school_name",window:"État actuel, comptes de test exclus"},{text:profiles.error?"La répartition des établissements reste indisponible.":`${geo.schools.length} établissements ou libellés recensés ; ${geo.excluded} comptes de test exclus (démo ou Science Factor). Le nom d’un établissement est un indice, pas une géolocalisation vérifiée.`,source:"profiles",window:"État actuel"}];}

export function networkInsights(error:boolean, stats:ReturnType<typeof networkStats>, data:NetworkData):Insight[] {return [{text:error?"La lecture du réseau est incomplète. Impossible de compter les élèves reliés.":`Sur ${stats.total} élèves, ${stats.connected} ont au moins un ami et ${stats.isolated} sont isolés. Le plus grand groupe en relie ${stats.largest}.`,source:"friendships / profiles / profiles_public",window:"État actuel, comptes de test exclus"},{text:error?"Les groupes et le degré moyen restent indisponibles.":`${stats.groups} groupes d’au moins deux élèves ; ${data.links.length} liens uniques, soit ${number(stats.average,2)} amis par élève en moyenne, isolés inclus.`,source:"friendships / profiles",window:"État actuel, amitiés acceptées"}];}

export function pupilInsights(xp:ViewResult<DailyXp>, profile:ViewResult<ProfileDetail>, p:ProfileDetail|undefined, badges:ViewResult<PupilBadge>, friends:ViewResult<Friendship>, id:string):Insight[] {return [{text:xp.error?"L’historique XP n’a pas répondu.":`${sum(xp.data,"amount")} XP sur ${xp.data.length} jours renseignés dans les 30 derniers relevés.`,source:"daily_xp",window:"30 derniers jours renseignés"},{text:profile.error?"Le profil n’a pas répondu.":`Série actuelle : ${p?.streak??0} jours. ${badges.error?"Badges indisponibles.":`Badges acquis : ${badges.data.length}.`} ${friends.error?"Amitiés indisponibles.":`${new Set(friends.data.map(f=>f.user_id===id?f.friend_id:f.user_id)).size} amis acceptés.`}`,source:"profiles / user_badges / friendships",window:"État actuel"}];}
