import { PageHeader, DenseTable } from "./analytics-ui";
import { Bars, TimeChart, Heatmap, Gauge, type Series, type ChartRow } from "./charts";
import { ChartPanel, Findings, Funnel, PreviewBanner, referenceDate, type SearchProps } from "./story";
import { readView, type ViewName, type AiQuality, type Onboarding, type Retention } from "@/lib/views";
import { group, funnel, pageInsights, type Dataset } from "@/lib/insights";
type Panel={view:ViewName;title:string;window:string;kind?:"bars"|"time"|"funnel"|"heatmap"|"quality";label?:string;value?:string;unit?:string;series?:Series[];caveat?:string;average?:boolean;stacked?:boolean;thresholds?:boolean;columns?:[string,string][]};
const p=(view:ViewName,title:string,window:string,rest:Omit<Panel,"view"|"title"|"window">):Panel=>({view,title,window,...rest});
const time=(view:ViewName,title:string,series:[string,string][],rest:Partial<Panel>={}):Panel=>p(view,title,"30 jours",{kind:"time",series:series.map(([key,name])=>({key,name})),...rest});
const bar=(view:ViewName,title:string,window:string,label:string,value:string,rest:Partial<Panel>={}):Panel=>p(view,title,window,{kind:"bars",label,value,...rest});
const demo="Démo et dev inclus dans cette vue.";
export const pageSpecs:Record<string,{title:string;description:string;panels:Panel[]}>={
 retention:{title:"Rétention et usage",description:"Revenir, explorer, rester. Lire la fidélité à travers les cohortes et les parcours.",panels:[
 p("v_retention","Est-ce qu’ils reviennent ?","Cohortes disponibles",{kind:"heatmap"}),bar("v_ecrans","Les écrans qui comptent","7 jours","ecran","vues"),bar("v_sorties","Où se termine la visite ?","7 jours","ecran","sorties",{caveat:demo}),time("v_demo","De la découverte au compte",[["demos","Découvertes"],["convertis","Conversions"]],{window:"60 jours"}),bar("v_versions","Les versions utilisées","30 jours","app_version","evenements",{unit:"événements",caveat:"Les élèves peuvent utiliser plusieurs versions ; leurs effectifs ne sont pas additionnés."}),bar("v_demarrage","Démarrer sans attendre","14 jours","appareil","p95_ms",{unit:"ms au 95e percentile",caveat:"Chaque barre représente un appareil, une version et une plateforme. Les percentiles ne sont pas additionnés."})]},
 entonnoir:{title:"Entonnoir",description:"De la première ouverture au premier compte. Chaque marche représente des installations, pas des élèves.",panels:[
 p("v_onboarding","Le chemin jusqu’au compte","30 jours, jour d’arrivée",{kind:"funnel"}),bar("v_onboarding_abandons","La dernière étape avant de partir","30 jours","derniere_etape","installs",{caveat:"Les comptes ajoutés sont exclus de cette répartition des abandons."}),time("v_onboarding","Arrivées et comptes ajoutés",[["arrivees","Installations arrivées"],["compte_ajoute","Comptes ajoutés"]]),bar("v_onboarding_echecs","Ce qui empêche la connexion","14 jours","motif","n",{caveat:demo}),time("v_activation","Les premières minutes",[["comptes","Comptes"],["ont_vu_leurs_donnees","Données vues"],["ont_touche_ia_j0","IA essayée à J0"]],{window:"60 jours"})]},
 services:{title:"Services scolaires",description:"Les connecteurs qui tiennent et ceux qui empêchent de commencer.",panels:[bar("v_services","Les services des actifs","7 jours","service","actifs_7j"),bar("v_services","Les synchronisations en échec","7 jours","service","echec_pct_7j",{unit:"%",thresholds:true}),bar("v_services","Le délai de synchronisation","Fenêtre fournie par la vue","service","sync_mediane_ms",{unit:"ms, médiane"}),bar("v_activation","Les premières données par service","60 jours, J0","service","ont_vu_leurs_donnees")]},
 ia:{title:"Moteur IA",description:"Ce qui est servi, ce que cela coûte et ce qui échoue. Les refus attendus restent distincts des pannes.",panels:[time("v_ai_pouls","Le rythme du moteur",[["requetes","Requêtes"],["echecs","Pannes"],["refus","Refus attendus"]],{average:true}),time("v_ai_pouls","Le coût jour après jour",[["cout_usd_estime","Coût estimé"]],{unit:"USD",average:true}),time("v_ai_pouls_routes","D’où viennent les quiz ?",[["depuis_le_cours","Cours"],["depuis_le_programme","Programme"],["depuis_la_banque","Banque"],["mutualisees","Mutualisées"]],{stacked:true,window:"Fenêtre fournie par la vue",caveat:"Une part programme durablement haute peut signaler un défaut de collecte des cours. Mutualisées : réutilisations selon la vue des routes."}),p("v_ai_quality","La qualité perçue","30 jours",{kind:"quality"}),bar("v_ia","Réussite côté élève","14 jours","tache","ok_pct",{unit:"%",caveat:demo}),bar("v_ia_locale","Les générations sur l’appareil","30 jours","modele","generations",{caveat:demo}),p("v_ia_entonnoir","Après la génération, l’usage","30 jours",{columns:[["tache","Tâche"],["moteur","Moteur"],["demandes","Demandes"],["reussies","Réussies"],["suivies_d_un_lancement","Lancements"],["suivies_d_une_fin","Terminées"],["taux_d_usage_pct","Usage, %"]]}),time("v_ai_options","La forme des réponses",[["generations_mesurees","Générations mesurées (dénominateur)"],["modele_moins_de_4","Moins de 4 options"],["repetitions","Répétitions"]],{caveat:"Le dénominateur est le nombre de générations mesurées, pas le nombre de quiz servis."}),bar("v_ai_cache","Les réutilisations du cache","État actuel","task","reutilisations"),p("v_ai_repeats","Les contenus servis plusieurs fois","Fenêtre fournie par la vue",{columns:[["content_key","Contenu"],["fois_servi","Fois servi"],["chemins","Chemins"],["dernier","Dernière fois"]]}),time("v_ai_rebond","Après un contexte trop mince",[["refus_contexte_mince","Refus"],["rebonds_vers_la_banque","Vers la banque"],["rebonds_vers_generation","Vers la génération"]],{window:"Fenêtre fournie par la vue",caveat:"Non interprétable sans trafic réel."})]},
 banque:{title:"Banque de questions",description:"La qualité à entretenir. Les contenus signalés et les alias inconnus ouvrent la file de révision.",panels:[p("v_ai_quality","Ce que disent les votes","30 jours",{kind:"quality"}),bar("v_ai_bank_health","Les contenus à relire","État actuel","title","signalements"),bar("v_ai_bank_questions","Les questions signalées","État actuel","title","eleves_signalants",{caveat:"Nombre d’élèves par question, sans addition entre questions."}),p("v_ai_themes","Les alias à réviser en priorité","Fenêtre fournie par la vue",{columns:[["slug","Alias"],["occurrences","Occurrences"],["connu_en_banque","Connu en banque"],["derniere_fois","Dernière fois"]]}),p("v_ai_bank_health","L’inventaire de la banque","État actuel",{columns:[["title","Contenu"],["subject_canon","Matière"],["level","Classe"],["quality","Qualité sur 5"],["published","Publié"],["signalements","Signalements"]]})]},
 rituel:{title:"Rituel",description:"Les petits efforts qui deviennent une habitude. Observer les journées validées et l’utilité des rappels.",panels:[time("v_gamification","Les journées qui tiennent",[["journees_validees","Journées validées"],["eleves_effort","Élèves ayant fait un effort"],["series_rompues","Séries rompues"]],{average:true,caveat:demo}),bar("v_efforts","Ce que les élèves travaillent","30 jours","kind","n",{caveat:demo}),bar("v_notifs","Les rappels ouverts","30 jours","notif_type","ouvertes",{caveat:demo}),p("v_notifs_efficacite","À quelle heure les rappels sont-ils ouverts ?","Fenêtre fournie par la vue",{kind:"bars",label:"heure_prevue",value:"ouverture_pct",unit:"% des notifications planifiées",caveat:"Taux pondérés par les notifications planifiées. Démo et dev inclus. L’horaire n’est pas une preuve de causalité."}),bar("v_notif_permissions","L’autorisation des notifications","État actuel","statut","personnes")]},
 erreurs:{title:"Erreurs",description:"Distinguer les pannes, les arrêts brutaux et les angles morts de l’instrumentation.",panels:[bar("v_crashs","Les familles de crashs","14 jours","gravite","n",{caveat:demo}),time("v_morts_brutales","Les arrêts brutaux",[["n","Arrêts brutaux"]],{window:"14 jours",caveat:"La vue des crashs ne fournit pas de série quotidienne. Cette courbe concerne uniquement les fins brutales."}),bar("v_echecs","Les échecs par famille","14 jours","event_name","n"),bar("v_echecs_detail","Les motifs à traiter","7 jours","motif","n"),p("v_sante_instrumentation","Les angles morts de la mesure","14 jours",{columns:[["famille","Famille"],["evenement","Événement"],["n_14j","Occurrences"],["etat","État"],["description","Description"]]}),p("v_crashs","Le contexte des crashs","14 jours",{caveat:demo,columns:[["motif","Motif"],["ecran","Écran"],["app_version","Version"],["platform","Plateforme"],["n","Occurrences"]]})]},
};
type Row=Record<string,string|number|null|boolean|string[]>;
function renderPanel(spec:Panel,raw:object[],end:string){let rows=raw as Row[];
 if(spec.view==="v_ai_themes")rows=[...rows].sort((a,b)=>Number(a.connu_en_banque)-Number(b.connu_en_banque)||Number(b.occurrences)-Number(a.occurrences));
 if(!rows.length)return <p className="empty-chart">Aucune donnée disponible pour cette analyse.</p>;
 if(spec.kind==="funnel")return <Funnel steps={funnel(raw as Onboarding[])}/>;
 if(spec.kind==="heatmap")return <Heatmap rows={raw as Retention[]}/>;
 if(spec.kind==="quality")return <div className="grid gap-3 sm:grid-cols-2">{(raw as AiQuality[]).map((r,i)=><Gauge key={i} label={`${r.route} · ${r.model}`} value={r.votes>0?r.pct_likes:null} detail={`${r.likes} avis positifs / ${r.votes} votes · ${r.quiz_servis} quiz servis · ${r.votes_avec_signalement} signalements · prompt ${r.prompt_version}`}/>)}</div>;
 if(spec.kind==="time") {const map=new Map<string,ChartRow>();for(const row of rows){const label=String(row.jour).slice(0,10);const item=map.get(label)??{label};for(const s of spec.series??[])item[s.key]=Number(item[s.key]??0)+Number(row[s.key]??0);map.set(label,item);}return <TimeChart title={spec.title} rows={[...map.values()]} series={spec.series??[]} stacked={spec.stacked} average={spec.average} end={end} unit={spec.unit}/>;}
 if(spec.kind==="bars") {
  if(spec.view==="v_onboarding_abandons")rows=rows.filter(r=>!String(r.derniere_etape).startsWith("8."));
  let values=group(rows,spec.label!,spec.value!);
  if(spec.view==="v_demarrage")values=rows.map(r=>({label:`${r.appareil} · ${r.platform} · ${r.app_version}`,value:Number(r.p95_ms)}));
  if(spec.view==="v_ai_bank_questions")values=rows.map(r=>({label:`${r.title} · ${r.question_id}`,value:Number(r.eleves_signalants)}));
  if(spec.view==="v_ia")values=rows.map(r=>({label:`${r.tache} · ${r.moteur}`,value:Number(r.ok_pct)}));
  if(spec.view==="v_notifs_efficacite") {const map=new Map<string,{sent:number;open:number}>();for(const r of rows){const key=String(r.heure_prevue).split(":")[0].padStart(2,"0")+" h";const item=map.get(key)??{sent:0,open:0};item.sent+=Number(r.planifiees);item.open+=Number(r.ouvertes);map.set(key,item);}values=[...map].filter(([,v])=>v.sent>0).map(([label,v])=>({label:`${label} (${v.open}/${v.sent})`,value:100*v.open/v.sent}));}
  return <Bars title={spec.title} rows={values} unit={spec.unit} thresholds={spec.thresholds}/>;
 }
 return <DenseTable label={spec.title} rows={rows} columns={(spec.columns??[]).map(([key,label])=>({key,label}))}/>;
}
export async function AnalyticsPage({page,searchParams}:{page:string}&SearchProps){const preview=(await searchParams).apercu==="1",spec=pageSpecs[page];const names=[...new Set([...spec.panels.map(p=>p.view),...(page==="ia"?["v_pouls" as const]:[])])];const results=await Promise.all(names.map(async name=>({name,...await readView(name,{preview})})));const data=Object.fromEntries(results.map(r=>[r.name,r.data])) as Dataset;return <><PreviewBanner preview={preview}/><PageHeader title={spec.title} description={spec.description}/><Findings items={pageInsights(page,data,referenceDate(preview))}/><div className="grid items-start gap-5 xl:grid-cols-2">{spec.panels.map((panel,i)=><ChartPanel key={i} title={panel.title} source={panel.view} window={panel.window} caveat={panel.caveat} error={results.find(r=>r.name===panel.view)?.error}>{renderPanel(panel,data[panel.view]??[],referenceDate(preview))}</ChartPanel>)}</div></>;}
