import { AlertCircle, Database, Info } from "lucide-react";
import { formatValue } from "@/lib/views";

export function PageHeader({ title, description }: { title:string; description:string }) { return <header className="mb-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#CDA1F9]">Pilotage interne</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">{title}</h1><p className="mt-2 max-w-3xl text-sm text-[#A8A0B4]">{description}</p></header>; }

export function EmptyProduction({ view, error=false, caveat }: { view:string; error?:boolean; caveat?:string }) { return <div className="rounded-2xl border border-dashed border-[#332D3D] bg-[#09060C] px-5 py-6 text-sm"><div className="flex gap-3"><AlertCircle className={error ? "mt-0.5 size-4 text-[#FF8B95]" : "mt-0.5 size-4 text-[#CDA1F9]"}/><div><p className="font-semibold">{error ? `La vue ${view} n’a pas répondu.` : "Aucune donnée de production pour l’instant : la 1.3.0 n’est pas publiée."}</p>{caveat && <p className="mt-2 text-[#A8A0B4]">{caveat}</p>}<p className="mt-3 flex items-center gap-1 font-mono text-xs text-[#A8A0B4]"><Database className="size-3" />Source : {view}</p></div></div></div>; }

export function Metric({ question, value, detail, view, tone="lilas" }: { question:string; value:string | number; detail?:string; view:string; tone?:"lilas"|"menthe"|"peche"|"rose" }) { const colors = { lilas:"bg-[#27212C]", menthe:"bg-[#173230]", peche:"bg-[#3A2820]", rose:"bg-[#38222B]" }; return <section className={`rounded-2xl border border-[#332D3D] p-4 ${colors[tone]}`}><p className="text-sm text-[#CDC8D6]">{question}</p><p className="mt-2 font-display text-3xl leading-none">{formatValue(value)}</p>{detail && <p className="mt-2 text-xs text-[#A8A0B4]">{detail}</p>}<p className="mt-3 font-mono text-[10px] text-[#A8A0B4]">Source : {view}</p></section>; }

export function ViewPanel({ title, view, children, error, caveat, empty=false, className="" }: { title:string; view:string; children?:React.ReactNode; error?:boolean; caveat?:string; empty?:boolean; className?:string }) { return <section className={`rounded-3xl border border-[#332D3D] bg-[#1D1822] p-5 ${className}`}><div className="mb-4 flex flex-wrap items-start justify-between gap-2"><div><h2 className="font-display text-xl">{title}</h2><p className="mt-1 font-mono text-[11px] text-[#A8A0B4]">Source : {view}</p></div>{caveat && <p className="max-w-sm rounded-full bg-[#38222B] px-3 py-1 text-xs text-[#FFA1AC]"><Info className="mr-1 inline size-3" />{caveat}</p>}</div>{empty || error ? <EmptyProduction view={view} error={error} caveat={caveat} /> : children}</section>; }

export function DenseTable({ rows, columns, label }: { rows:object[]; columns:{ key:string; label:string; emphasis?:boolean }[]; label:string }) { return <div className="overflow-x-auto"><table aria-label={label} className="w-full min-w-[560px] text-left text-sm"><thead className="border-b border-[#332D3D] text-xs text-[#A8A0B4]"><tr>{columns.map((column) => <th className="px-3 py-2 font-semibold" key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row, index) => { const record=row as Record<string,unknown>; return <tr className="border-b border-[#332D3D]/60 last:border-0" key={String(record.id ?? record.jour ?? record.event_name ?? index)}>{columns.map((column) => {const value=record[column.key];const state=column.key==="etat"?String(value):"";const stateClass=state==="calme"?"text-[#8FD8C2]":state==="à regarder"?"text-[#F6C86B]":state==="aucune donnée de production"?"text-[#A8A0B4]":state?"text-[#FFA1AC]":"";return <td className={`px-3 py-3 ${column.emphasis ? "font-semibold text-[#F3F0F9]" : "text-[#CDC8D6]"} ${stateClass}`} key={column.key}>{formatValue((value ?? null) as string | number | boolean | string[] | null)}</td>;})}</tr>; })}</tbody></table></div>; }

export function BarList({ rows, label, valueKey }: { rows:Record<string, unknown>[]; label:string; valueKey:string }) { const max = Math.max(...rows.map((row) => Number(row[valueKey]) || 0), 1); return <div aria-label={label} className="space-y-3">{rows.slice(0, 12).map((row, index) => <div key={`${String(row[label])}-${index}`}><div className="mb-1 flex justify-between gap-4 text-xs"><span className="truncate text-[#CDC8D6]">{formatValue((row[label] ?? null) as string | number | boolean | string[] | null)}</span><span className="font-mono text-[#F3F0F9]">{formatValue((row[valueKey] ?? null) as string | number | boolean | string[] | null)}</span></div><div className="h-2 overflow-hidden rounded-full bg-[#09060C]"><div className="h-full rounded-full bg-[#B580F4]" style={{ width: `${(Number(row[valueKey]) / max) * 100}%` }} /></div></div>)}</div>; }
