"use client";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, ComposedChart, Pie, PieChart, ReferenceArea, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useSyncExternalStore, type ReactNode } from "react";
const noSubscription=()=>()=>{};
/** false pendant le rendu serveur, true une fois dans le navigateur, sans setState dans un effet. */
function useMounted(){return useSyncExternalStore(noSubscription,()=>true,()=>false);}
/** Largeur d'écran étroite (téléphone) lue sans effet : les graphiques Recharts ne connaissent pas les media queries CSS. */
const narrowQuery="(max-width: 640px)";
function subscribeNarrow(cb:()=>void){const mq=window.matchMedia(narrowQuery);mq.addEventListener("change",cb);return()=>mq.removeEventListener("change",cb);}
export function useNarrow(){return useSyncExternalStore(subscribeNarrow,()=>window.matchMedia(narrowQuery).matches,()=>false);}
/** Recharts numérote ses clipPath différemment sur le serveur et dans le navigateur, ce qui casse l'hydratation :
 *  on ne rend le graphique qu'une fois monté, en gardant un gabarit de même hauteur pendant le rendu serveur. */
function ChartGate({children}:{children:ReactNode}){const mounted=useMounted();return mounted?<>{children}</>:<div className="h-full w-full animate-pulse rounded-xl bg-[#09060C]" aria-hidden="true"/>;}
import { number } from "@/lib/insights";
import type { Retention } from "@/lib/views";
/** Six teintes dans un ordre fixe, validées daltonisme sur le fond #1D1822 (ΔE adjacent ≥ 8,4) : lilas, orange, vert, ambre, bleu, rose. Jamais recyclées au-delà de huit. */
export const palette=["#A56BF0","#D95926","#199E70","#C98500","#3987E5","#D55181","#9085E9","#E66767"];
export type ChartRow = {label:string;[key:string]:string|number|null};
/** Les clés techniques des vues, en français lisible. Une clé inconnue s'affiche telle quelle. */
const LABELS:Record<string,string>={tle:"Terminale","1re":"Première","2de":"Seconde","3e":"Troisième","4e":"Quatrième","5e":"Cinquième","6e":"Sixième",primaire:"Primaire",autre:"Autre",inconnu:"Inconnu",inconnue:"Inconnue",pronote:"Pronote",ecoledirecte:"ÉcoleDirecte",skolengo:"Skolengo",appscho:"AppScho",canvas:"Canvas",moodle:"Moodle",webuntis:"WebUntis",iOS:"iPhone / iPad",Android:"Android",Mobile:"Téléphone",Tablet:"Tablette",Desktop:"Ordinateur",granted:"Autorisées",denied:"Refusées",undetermined:"Pas encore demandé",fatal:"Fatal",rejet:"Promesse rejetée",frontiere:"Frontière de rendu",account_connected:"Compte connecté",homework_done:"Devoir fait",quiz_submitted:"Quiz rendu",flashcards_session:"Session de cartes",pomodoro_completed:"Focus terminé",pomodoro_partial:"Focus interrompu",effort_daily:"Rappel quotidien",effort_reconquest:"Reconquête",effort_saver:"Sauvetage de série",app_error:"Erreur applicative",connector_sync_failed:"Synchro ENT échouée",unhandled_rejection:"Promesse orpheline",ai_generation_failed:"Génération IA échouée",profile_adoption_failed:"Adoption de profil refusée",app_crash:"Crash JS",screen_error:"Écran en erreur",login_failed:"Connexion échouée",vivant:"Vivant",anecdotique:"Anecdotique","jamais vu":"Jamais vu",cloud:"Cloud",local:"Sur l’appareil",quiz:"Quiz",flashcards:"Flashcards",revision_sheet:"Fiche de révision",mindmap:"Carte mentale",help:"Aide",revision:"Fiche",quiz_stream:"Quiz"};
export const pretty=(label:string)=>LABELS[label]??label;
export type Series = {key:string;name:string};
const tooltip={background:"#08040A",border:"1px solid #332D3D",borderRadius:16,color:"#F3F0F9",fontSize:12};
const tick={fill:"#A8A0B4",fontSize:11};
export function TimeChart({rows,series,title,stacked=false,average=false,end,unit=""}:{rows:ChartRow[];series:Series[];title:string;stacked?:boolean;average?:boolean;end:string;unit?:string}){
 const narrow=useNarrow();
 const ordered=[...rows].sort((a,b)=>a.label.localeCompare(b.label));
 const byDate=new Map(ordered.map(r=>[r.label.slice(0,10),r]));
 const first=Date.parse(ordered[0]?.label??""),last=Date.parse(ordered[ordered.length-1]?.label??"");
 const sorted:ChartRow[]=Number.isFinite(first)&&Number.isFinite(last)&&last-first<370*86400000?Array.from({length:Math.floor((last-first)/86400000)+1},(_,i)=>{const label=new Date(first+i*86400000).toISOString().slice(0,10);return byDate.get(label)??{label,...Object.fromEntries(series.map(s=>[s.key,null]))};}):ordered;
 const data:ChartRow[]=sorted.map((r,i)=>{const slice=sorted.slice(Math.max(0,i-6),i+1);const complete=slice.length===7&&Date.parse(r.label)-Date.parse(slice[0].label)===6*86400000&&slice.every(v=>typeof v[series[0].key]==="number");return {...r,average:complete?slice.reduce((s,v)=>s+Number(v[series[0].key]),0)/7:null};});
 const start=new Date(Date.parse(end+"T00:00:00Z")-6*86400000).toISOString().slice(0,10);
 return <div role="img" aria-label={`${title}. ${series.map(s=>s.name).join(", ")}. ${unit}`}><p className="mb-3 text-xs text-[#A8A0B4]">Zone lilas : 7 derniers jours{average?" · Pointillés : moyenne mobile sur 7 jours complets":""}{unit?` · ${unit}`:""}</p>{!rows.length?<p className="empty-chart">Aucune donnée disponible pour cette courbe.</p>:<div className="h-64 min-w-0 sm:h-72"><ChartGate><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:640,height:288}}><ComposedChart data={data} margin={{top:10,right:8,left:narrow?-12:0,bottom:4}} accessibilityLayer><CartesianGrid stroke="#332D3D" vertical={false}/><XAxis dataKey="label" tickFormatter={v=>String(v).slice(5).split("-").reverse().join("/")} tick={tick} minTickGap={narrow?48:35} axisLine={false} tickLine={false}/><YAxis tick={tick} width={48} tickFormatter={v=>number(Number(v),3)} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltip} labelFormatter={v=>String(v)} formatter={(v:number)=>number(v,4)}/><Legend wrapperStyle={{fontSize:12,paddingTop:12}} iconType="circle" iconSize={8}/><ReferenceArea x1={data.find(r=>r.label>=start)?.label} x2={data[data.length-1]?.label} fill="#B580F4" fillOpacity={0.08}/>{series.map((s,i)=><Area key={s.key} dataKey={s.key} name={s.name} type="monotone" stroke={palette[i%8]} fill={palette[i%8]} fillOpacity={stacked?0.7:0.1} strokeWidth={2} stackId={stacked?"routes":undefined} isAnimationActive={false} connectNulls={false} dot={data.filter(r=>r[s.key]!==null).length<=2}/>)}{average&&<Line name={`Moyenne 7 j · ${series[0].name}`} dataKey="average" stroke="#F3F0F9" strokeDasharray="4 4" dot={false} isAnimationActive={false}/>}</ComposedChart></ResponsiveContainer></ChartGate></div>}</div>;
}
export function Bars({rows,title,unit="",thresholds=false}:{rows:{label:string;value:number}[];title:string;unit?:string;thresholds?:boolean}){const narrow=useNarrow();const data=[...rows].map(r=>({...r,label:pretty(r.label)})).sort((a,b)=>b.value-a.value);const labelWidth=narrow?118:155;return <div role="img" aria-label={`${title}, ${unit||"nombre"}`}><p className="mb-2 text-xs text-[#A8A0B4]">{thresholds?"Calme : moins de 5 % · À regarder : 5 % · Critique : 20 %":`${unit||"Nombre"} · du plus élevé au plus faible`}</p>{!data.length?<p className="empty-chart">Aucune répartition disponible.</p>:<div style={{height:Math.max(160,data.length*40)}}><ChartGate><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:640,height:Math.max(160,data.length*40)}}><BarChart data={data} layout="vertical" margin={{left:0,right:36,top:4,bottom:0}} accessibilityLayer><CartesianGrid stroke="#332D3D" horizontal={false}/><XAxis type="number" tick={tick} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="label" width={labelWidth} tick={{fill:"#CDC8D6",fontSize:11}} axisLine={false} tickLine={false} tickFormatter={(v:string)=>v.length>(narrow?18:26)?v.slice(0,narrow?17:25)+"…":v}/><Tooltip contentStyle={tooltip} formatter={(v:number)=>`${number(v)} ${unit}`}/><Bar dataKey="value" name={unit||"Nombre"} radius={[0,6,6,0]} maxBarSize={16} isAnimationActive={false} label={{position:"right",fill:"#F3F0F9",fontSize:11,formatter:(v:number)=>number(v)}}>{data.map((r,i)=><Cell key={i} fill={thresholds?(r.value>=20?"#E14D5E":r.value>=5?"#E8A13C":"#2FA97C"):palette[0]}/>)}</Bar></BarChart></ResponsiveContainer></ChartGate></div>}</div>;}
/** Camembert évidé : au plus six parts nommées (le reste va dans « Autres »), un chiffre au centre, la liste des parts à côté avec valeur et part en pour cent. */
export function Donut({rows,title,unit="",center,centerLabel,maxSlices=6}:{rows:{label:string;value:number}[];title:string;unit?:string;center?:string;centerLabel?:string;maxSlices?:number}){
 const sorted=[...rows].filter(r=>r.value>0).map(r=>({...r,label:pretty(r.label)})).sort((a,b)=>b.value-a.value);
 const data=sorted.length>maxSlices?[...sorted.slice(0,maxSlices-1),{label:`Autres (${sorted.length-maxSlices+1})`,value:sorted.slice(maxSlices-1).reduce((n,r)=>n+r.value,0)}]:sorted;
 const total=data.reduce((n,r)=>n+r.value,0);
 if(!data.length)return <p className="empty-chart">Aucune répartition disponible.</p>;
 return <div role="img" aria-label={`${title} : ${data.map(r=>`${r.label} ${number(r.value)} (${number(100*r.value/total)} %)`).join(", ")}`} className="@container"><div className="flex flex-col items-center gap-4 @md:flex-row @md:items-center">
  <div className="relative h-44 w-44 shrink-0 sm:h-48 sm:w-48"><ChartGate><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:192,height:192}}><PieChart accessibilityLayer><Pie data={data} dataKey="value" nameKey="label" innerRadius="66%" outerRadius="100%" paddingAngle={data.length>1?2:0} stroke="#1D1822" strokeWidth={2} isAnimationActive={false} startAngle={90} endAngle={-270}>{data.map((r,i)=><Cell key={r.label} fill={palette[i%8]}/>)}</Pie><Tooltip contentStyle={tooltip} formatter={(v:number)=>`${number(v)} ${unit} · ${number(100*v/total)} %`}/></PieChart></ResponsiveContainer></ChartGate><div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="font-display text-3xl leading-none">{center??number(total)}</p><p className="mt-1 text-[11px] text-[#A8A0B4]">{centerLabel??(unit||"au total")}</p></div></div></div>
  <ul className="w-full min-w-0 flex-1 space-y-1.5 text-sm">{data.map((r,i)=><li key={r.label} className="flex items-center gap-2.5"><span className="size-2.5 shrink-0 rounded-full" style={{background:palette[i%8]}} aria-hidden="true"/><span className="min-w-0 flex-1 truncate text-[#CDC8D6]">{r.label}</span><span className="tabular-nums text-[#F3F0F9]">{number(r.value)}</span><span className="w-12 text-right tabular-nums text-xs text-[#A8A0B4]">{number(100*r.value/total)} %</span></li>)}</ul>
 </div></div>;
}
export function Sparkline({values,label}:{values:(number|null)[];label:string}){return values.filter(v=>v!==null).length<2?<p className="mt-4 text-xs text-[#A8A0B4]">Historique indisponible</p>:<div className="mt-2 h-12" role="img" aria-label={label}><ChartGate><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:240,height:48}}><AreaChart data={values.map(value=>({value}))} margin={{top:2,right:0,left:0,bottom:0}}><Area dataKey="value" stroke="#CDA1F9" strokeWidth={1.5} fill="#B580F4" fillOpacity={0.16} isAnimationActive={false} type="monotone"/></AreaChart></ResponsiveContainer></ChartGate></div>;}
export function Heatmap({rows}:{rows:Retention[]}){return <div className="overflow-x-auto"><table aria-label="Rétention des cohortes à J1, J7 et J30" className="w-full min-w-[420px] text-sm"><thead><tr><th className="p-2 text-left text-xs font-semibold text-[#A8A0B4]">Cohorte · élèves</th>{[1,7,30].map(n=><th key={n} className="text-xs font-semibold text-[#A8A0B4]">J{n}</th>)}</tr></thead><tbody>{[...rows].sort((a,b)=>b.cohorte.localeCompare(a.cohorte)).map(r=><tr key={r.cohorte}><th className="whitespace-nowrap p-2 text-left font-normal text-[#CDC8D6]">{r.cohorte.slice(8,10)}/{r.cohorte.slice(5,7)}<span className="ml-2 text-xs text-[#A8A0B4]">{r.eleves} élèves</span></th>{([r.j1_pct,r.j7_pct,r.j30_pct]).map((v,i)=><td key={i} className="border-4 border-[#1D1822] rounded-xl p-2 text-center text-xs font-bold sm:text-sm" style={{background:v===null?"#09060C":v>=80?"#CDA1F9":v>=60?"#B580F4":v>=30?"#503766":"#27212C",color:v!==null&&v>=60?"#1A1224":v===null?"#6E6680":"#F3F0F9"}}>{v===null?"·":`${number(v)} %`}</td>)}</tr>)}</tbody></table><p className="mt-3 text-xs text-[#A8A0B4]">Plus le lilas est clair, plus les élèves reviennent. Un point : cohorte trop récente, la fenêtre n’est pas refermée.</p></div>;}
export function Gauge({value,label,detail}:{value:number|null;label:string;detail:string}){return <div className="rounded-2xl bg-[#09060C] p-4" role="img" aria-label={`${label} : ${value===null?"non mesuré":number(value)+" %"}, ${detail}`}><p className="text-sm">{label}</p><p className="mt-3 font-display text-3xl">{value===null?"Non mesuré":`${number(value)} %`}</p><div className="my-3 h-2 rounded-full bg-[#332D3D]"><div className="h-2 rounded-full bg-[#B580F4]" style={{width:`${Math.max(0,Math.min(100,value??0))}%`}}/></div><p className="text-xs text-[#A8A0B4]">{detail}</p></div>;}
