"use client";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, ComposedChart, ReferenceArea, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useSyncExternalStore, type ReactNode } from "react";
const noSubscription=()=>()=>{};
/** false pendant le rendu serveur, true une fois dans le navigateur, sans setState dans un effet. */
function useMounted(){return useSyncExternalStore(noSubscription,()=>true,()=>false);}
/** Recharts numérote ses clipPath différemment sur le serveur et dans le navigateur, ce qui casse l'hydratation :
 *  on ne rend le graphique qu'une fois monté, en gardant un gabarit de même hauteur pendant le rendu serveur. */
function ChartGate({children}:{children:ReactNode}){const mounted=useMounted();return mounted?<>{children}</>:<div className="h-full w-full animate-pulse rounded-xl bg-[#09060C]" aria-hidden="true"/>;}
import { number } from "@/lib/insights";
import type { Retention } from "@/lib/views";
export const palette=["#B580F4","#FF8B95","#8FD8C2","#FF9A78","#6FA8D4","#F6C86B","#CDA1F9","#FFA1AC"];
export type ChartRow = {label:string;[key:string]:string|number|null};
export type Series = {key:string;name:string};
const tooltip={background:"#08040A",border:"1px solid #332D3D",borderRadius:16,color:"#F3F0F9",fontSize:12};
export function TimeChart({rows,series,title,stacked=false,average=false,end,unit=""}:{rows:ChartRow[];series:Series[];title:string;stacked?:boolean;average?:boolean;end:string;unit?:string}){
 const ordered=[...rows].sort((a,b)=>a.label.localeCompare(b.label));
 const byDate=new Map(ordered.map(r=>[r.label.slice(0,10),r]));
 const first=Date.parse(ordered[0]?.label??""),last=Date.parse(ordered[ordered.length-1]?.label??"");
 const sorted:ChartRow[]=Number.isFinite(first)&&Number.isFinite(last)&&last-first<370*86400000?Array.from({length:Math.floor((last-first)/86400000)+1},(_,i)=>{const label=new Date(first+i*86400000).toISOString().slice(0,10);return byDate.get(label)??{label,...Object.fromEntries(series.map(s=>[s.key,null]))};}):ordered;
 const data:ChartRow[]=sorted.map((r,i)=>{const slice=sorted.slice(Math.max(0,i-6),i+1);const complete=slice.length===7&&Date.parse(r.label)-Date.parse(slice[0].label)===6*86400000&&slice.every(v=>typeof v[series[0].key]==="number");return {...r,average:complete?slice.reduce((s,v)=>s+Number(v[series[0].key]),0)/7:null};});
 const start=new Date(Date.parse(end+"T00:00:00Z")-6*86400000).toISOString().slice(0,10);
 return <div role="img" aria-label={`${title}. ${series.map(s=>s.name).join(", ")}. ${unit}`}><p className="mb-3 text-xs text-[#A8A0B4]">Zone lilas : 7 derniers jours{average?" · Pointillés : moyenne mobile sur 7 jours complets":""}{unit?` · ${unit}`:""}</p>{!rows.length?<p className="empty-chart">Aucune donnée disponible pour cette courbe.</p>:<div className="h-72 min-w-0"><ChartGate><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:640,height:288}}><ComposedChart data={data} margin={{top:10,right:12,left:0,bottom:4}} accessibilityLayer><CartesianGrid stroke="#332D3D" vertical={false}/><XAxis dataKey="label" tickFormatter={v=>String(v).slice(5).split("-").reverse().join("/")} tick={{fill:"#A8A0B4",fontSize:11}} minTickGap={35} axisLine={false} tickLine={false}/><YAxis tick={{fill:"#A8A0B4",fontSize:11}} width={48} tickFormatter={v=>number(Number(v),3)} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltip} labelFormatter={v=>String(v)} formatter={(v:number)=>number(v,4)}/><Legend wrapperStyle={{fontSize:12,paddingTop:12}}/><ReferenceArea x1={data.find(r=>r.label>=start)?.label} x2={data[data.length-1]?.label} fill="#B580F4" fillOpacity={0.08}/>{series.map((s,i)=><Area key={s.key} dataKey={s.key} name={s.name} type="linear" stroke={palette[i%8]} fill={palette[i%8]} fillOpacity={stacked?0.65:0.12} strokeWidth={2} stackId={stacked?"routes":undefined} isAnimationActive={false} connectNulls={false} dot={data.filter(r=>r[s.key]!==null).length<=2}/>)}{average&&<Line name={`Moyenne 7 j · ${series[0].name}`} dataKey="average" stroke="#F3F0F9" strokeDasharray="4 4" dot={false} isAnimationActive={false}/>}</ComposedChart></ResponsiveContainer></ChartGate></div>}</div>;
}
export function Bars({rows,title,unit="",thresholds=false}:{rows:{label:string;value:number}[];title:string;unit?:string;thresholds?:boolean}){const data=[...rows].sort((a,b)=>b.value-a.value);return <div role="img" aria-label={`${title}, ${unit||"nombre"}`}><p className="mb-2 text-xs text-[#A8A0B4]">{thresholds?"Calme : moins de 5 % · À regarder : 5 % · Critique : 20 %":`${unit||"Nombre"} · du plus élevé au plus faible`}</p>{!data.length?<p className="empty-chart">Aucune répartition disponible.</p>:<div style={{height:Math.max(180,data.length*42)}}><ChartGate><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:640,height:Math.max(180,data.length*42)}}><BarChart data={data} layout="vertical" margin={{left:0,right:24,top:4,bottom:0}} accessibilityLayer><CartesianGrid stroke="#332D3D" horizontal={false}/><XAxis type="number" tick={{fill:"#A8A0B4",fontSize:11}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="label" width={155} tick={{fill:"#CDC8D6",fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltip} formatter={(v:number)=>`${number(v)} ${unit}`}/><Bar dataKey="value" name={unit||"Nombre"} radius={[0,6,6,0]} maxBarSize={18} isAnimationActive={false} label={{position:"right",fill:"#F3F0F9",fontSize:11,formatter:(v:number)=>number(v)}}>{data.map((r,i)=><Cell key={i} fill={thresholds?(r.value>=20?"#E14D5E":r.value>=5?"#E8A13C":"#2FA97C"):palette[0]}/>)}</Bar></BarChart></ResponsiveContainer></ChartGate></div>}</div>;}
export function Sparkline({values,label}:{values:(number|null)[];label:string}){return values.filter(v=>v!==null).length<2?<p className="mt-4 text-xs text-[#A8A0B4]">Historique indisponible</p>:<div className="mt-2 h-12" role="img" aria-label={label}><ChartGate><ResponsiveContainer width="100%" height="100%" minWidth={0} initialDimension={{width:240,height:48}}><AreaChart data={values.map(value=>({value}))}><Area dataKey="value" stroke="#CDA1F9" fill="#B580F4" fillOpacity={0.16} isAnimationActive={false}/></AreaChart></ResponsiveContainer></ChartGate></div>;}
export function Heatmap({rows}:{rows:Retention[]}){return <div className="overflow-x-auto"><table aria-label="Rétention des cohortes à J1, J7 et J30" className="w-full text-sm"><thead><tr><th className="p-3 text-left">Cohorte · élèves</th>{[1,7,30].map(n=><th key={n}>J{n}</th>)}</tr></thead><tbody>{[...rows].sort((a,b)=>b.cohorte.localeCompare(a.cohorte)).map(r=><tr key={r.cohorte}><th className="p-3 text-left font-normal text-[#CDC8D6]">{r.cohorte}<span className="ml-2 text-xs text-[#A8A0B4]">{r.eleves} élèves</span></th>{([r.j1_pct,r.j7_pct,r.j30_pct]).map((v,i)=><td key={i} className="border-4 border-[#1D1822] rounded-xl p-3 text-center font-bold" style={{background:v===null?"#09060C":v>=80?"#CDA1F9":v>=60?"#B580F4":v>=30?"#503766":"#27212C",color:v!==null&&v>=60?"#1A1224":"#F3F0F9"}}>{v===null?"Non mesuré":`${number(v)} %`}</td>)}</tr>)}</tbody></table><p className="mt-3 text-xs text-[#A8A0B4]">Plus le lilas est clair, plus les élèves reviennent. Non mesuré : cohorte trop récente ou mesure absente.</p></div>;}
export function Gauge({value,label,detail}:{value:number|null;label:string;detail:string}){return <div className="rounded-2xl bg-[#09060C] p-4" role="img" aria-label={`${label} : ${value===null?"non mesuré":number(value)+" %"}, ${detail}`}><p className="text-sm">{label}</p><p className="mt-3 font-display text-3xl">{value===null?"Non mesuré":`${number(value)} %`}</p><div className="my-3 h-3 rounded-full bg-[#332D3D]"><div className="h-3 rounded-full bg-[#B580F4]" style={{width:`${Math.max(0,Math.min(100,value??0))}%`}}/></div><p className="text-xs text-[#A8A0B4]">{detail}</p></div>;}
