"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {geoConicConformal,geoPath,geoArea} from "d3-geo";
import {scaleLinear} from "d3-scale";
import type {RegionCollection} from "@/lib/region-types";
import type {School} from "@/lib/insights/geography";
export type Pupil={id:string;name:string;key:string;level:number|null;streak:number;className:string|null};
const drom=["Guadeloupe","Martinique","Guyane","La Réunion","Mayotte"];
const confianceLabel:Record<string,string>={exact:"annuaire, nom exact",unique:"annuaire, seul candidat",estime:"région estimée par le nom"};
export function FranceMap({geojson,schools,pupils,total,unlocated,initialSchool=null,preview=false}:{geojson:RegionCollection;schools:School[];pupils:Pupil[];total:number;unlocated:number;initialSchool?:string|null;preview?:boolean}){
 const [selected,setSelected]=useState<string|null>(initialSchool?schools.find(s=>s.key===initialSchool)?.region??null:null);
 const [school,setSchool]=useState<string|null>(initialSchool);
 const counts=useMemo(()=>{const counts=new Map<string,number>();for(const s of schools)if(s.region)counts.set(s.region,(counts.get(s.region)??0)+s.count);return counts;},[schools]);
 const {paths,color,max,dots}=useMemo(()=>{const geo=structuredClone(geojson);for(const f of geo.features){if(geoArea(f)>2*Math.PI){if(f.geometry.type==="Polygon")f.geometry.coordinates.forEach(r=>r.reverse());if(f.geometry.type==="MultiPolygon")f.geometry.coordinates.forEach(p=>p.forEach(r=>r.reverse()));}}
 const projection=geoConicConformal().parallels([44,49]).rotate([-3,0]).center([0,46.5]).fitSize([550,480],geo);const path=geoPath(projection);const max=Math.max(1,...counts.values());
 const dots=schools.filter(s=>s.lat!==null&&s.lon!==null&&!drom.includes(s.region??"")).map(s=>{const p=projection([s.lon!,s.lat!]);return p?{key:s.key,school:s.school,x:p[0],y:p[1],r:3+Math.sqrt(s.count)*2.2,count:s.count,commune:s.commune}:null;}).filter((d):d is NonNullable<typeof d>=>d!==null).sort((a,b)=>b.r-a.r); // les gros points dessous, les petits restent cliquables
 return {paths:geo.features.map(f=>({name:f.properties.nom,path:path(f)??""})),color:scaleLinear<string>().domain([0,max/2,max]).range(["#27212C","#7A55B8","#CDA1F9"]),max,dots};},[geojson,counts,schools]);
 const regionSchools=schools.filter(s=>s.region===selected).sort((a,b)=>b.count-a.count);
 const current=school?schools.find(s=>s.key===school)??null:null;
 const currentPupils=school?pupils.filter(p=>p.key===school).sort((a,b)=>a.name.localeCompare(b.name,"fr")):[];
 const pick=(s:School)=>{setSchool(s.key);if(s.region)setSelected(s.region);};
 return <div className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div><svg viewBox="-15 -15 580 510" className="max-h-[510px] w-full" role="img" aria-label={`Répartition par région : ${total-unlocated} élèves localisés, ${unlocated} non localisés`}><title>France métropolitaine, établissements rattachés à l’annuaire officiel</title>{paths.map(p=><path key={p.name} d={p.path} fill={color(counts.get(p.name)??0)} stroke={selected===p.name?"#F3F0F9":"#0E0911"} strokeWidth={selected===p.name?2.5:1.2} tabIndex={0} role="button" aria-label={`${p.name} : ${counts.get(p.name)??0} élèves`} onFocus={()=>setSelected(p.name)} onMouseEnter={()=>setSelected(p.name)} onClick={()=>{setSelected(p.name);setSchool(null);}} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(p.name);setSchool(null);}}}><title>{`${p.name} : ${counts.get(p.name)??0} élèves`}</title></path>)}{dots.map(d=><circle key={d.key} cx={d.x} cy={d.y} r={d.r} fill={school===d.key?"#F3F0F9":"#FF9A78"} fillOpacity={0.9} stroke="#0E0911" strokeWidth={1.2} tabIndex={0} role="button" aria-label={`${d.school} : ${d.count} élèves`} className="cursor-pointer" onClick={()=>pick(schools.find(s=>s.key===d.key)!)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();pick(schools.find(s=>s.key===d.key)!);}}}><title>{`${d.school}${d.commune?` · ${d.commune}`:""} : ${d.count} élève${d.count>1?"s":""}`}</title></circle>)}</svg><div className="mx-auto flex max-w-xs items-center gap-3 text-xs text-[#A8A0B4]"><span>0</span><div className="h-2 flex-1 rounded-full" style={{background:"linear-gradient(to right,#27212C,#7A55B8,#CDA1F9)"}}/><span>{max} élèves</span></div><p className="mt-2 text-center text-xs text-[#A8A0B4]">Un point orange par établissement rattaché à l’annuaire, sa taille suit ses effectifs. Toucher un point ou une région.</p></div>
 <div className="space-y-4"><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#173230] p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-[#8FD8C2]">Localisés</p><p className="mt-1 font-display text-3xl">{total-unlocated}<span className="ml-1 font-sans text-xs text-[#CDC8D6]">/ {total}</span></p></div><div className="rounded-2xl border border-[#E8A13C]/50 bg-[#3A2820] p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-[#FFB08F]">Non localisés</p><p className="mt-1 font-display text-3xl">{unlocated}</p></div></div>
 <div className="flex flex-wrap gap-2">{drom.map(r=><button key={r} onClick={()=>{setSelected(r);setSchool(null);}} className={`rounded-full border px-3 py-1.5 text-xs ${selected===r?"border-[#CDA1F9] bg-[#503766]":"border-[#332D3D] bg-[#27212C]"}`}>{r} · {counts.get(r)??0}</button>)}</div>
 <div className="min-h-44 rounded-2xl bg-[#09060C] p-4" aria-live="polite">{current?<><button onClick={()=>setSchool(null)} className="mb-2 text-xs text-[#CDA1F9]">← {current.region??"Retour"}</button><h3 className="font-bold leading-snug">{current.nomOfficiel??current.school}</h3><p className="mt-1 text-xs text-[#A8A0B4]">{[current.commune,current.departement?`${current.departement} (${current.departementCode})`:null,current.region].filter(Boolean).join(" · ")||"Localisation inconnue"}{current.confiance?` · ${confianceLabel[current.confiance]}`:""}</p><p className="mt-2 text-sm text-[#CDA1F9]">{current.count} élève{current.count>1?"s":""}</p><ul className="mt-3 space-y-1.5 text-sm">{currentPupils.map(p=><li key={p.id} className="flex items-baseline justify-between gap-3"><Link href={`/dashboard/eleves/${encodeURIComponent(p.id)}${preview?"?apercu=1":""}`} className="min-w-0 truncate font-semibold text-[#F3F0F9] underline decoration-[#503766] underline-offset-4 hover:decoration-[#CDA1F9]">{p.name}</Link><span className="shrink-0 text-xs text-[#A8A0B4]">{p.className??"classe ?"} · niv. {p.level??"?"} · {p.streak} j</span></li>)}</ul></>:selected?<><h3 className="font-bold">{selected}</h3><p className="mt-1 text-sm text-[#CDA1F9]">{counts.get(selected)??0} élèves · {regionSchools.length} établissement{regionSchools.length>1?"s":""}</p><ul className="mt-3 space-y-1.5 text-sm">{regionSchools.map(s=><li key={s.key}><button onClick={()=>pick(s)} className="flex w-full items-baseline justify-between gap-3 text-left hover:text-[#CDA1F9]"><span className="min-w-0 truncate">{s.nomOfficiel??s.school}{s.commune?<span className="text-xs text-[#A8A0B4]"> · {s.commune}</span>:null}</span><span className="shrink-0 tabular-nums text-xs text-[#A8A0B4]">{s.count}</span></button></li>)}</ul>{!regionSchools.length&&<p className="mt-3 text-xs text-[#A8A0B4]">Aucun établissement rattaché.</p>}</>:<><h3 className="font-bold">Explorer</h3><p className="mt-3 text-xs text-[#A8A0B4]">Touchez une région pour ses établissements, puis un établissement pour ses élèves.</p></>}</div></div></div>;
}
