"use client";
import {useMemo,useState} from "react";
import {geoConicConformal,geoPath,geoArea} from "d3-geo";
import {scaleLinear} from "d3-scale";
import type {RegionCollection} from "@/lib/region-types";
export type SchoolCount={school:string;region:string|null;count:number};
const drom=["Guadeloupe","Martinique","Guyane","La Réunion","Mayotte"];
export function FranceMap({geojson,schools,total,unlocated}:{geojson:RegionCollection;schools:SchoolCount[];total:number;unlocated:number}){
 const [selected,setSelected]=useState<string|null>(null);
 const counts=useMemo(()=>{const counts=new Map<string,number>();for(const s of schools)if(s.region)counts.set(s.region,(counts.get(s.region)??0)+s.count);return counts;},[schools]);
 const {paths,color,max}=useMemo(()=>{const geo=structuredClone(geojson);for(const f of geo.features){if(geoArea(f)>2*Math.PI){if(f.geometry.type==="Polygon")f.geometry.coordinates.forEach(r=>r.reverse());if(f.geometry.type==="MultiPolygon")f.geometry.coordinates.forEach(p=>p.forEach(r=>r.reverse()));}}
 const projection=geoConicConformal().parallels([44,49]).rotate([-3,0]).center([0,46.5]).fitSize([550,480],geo);const path=geoPath(projection);const max=Math.max(1,...counts.values());return {paths:geo.features.map(f=>({name:f.properties.nom,path:path(f)??""})),color:scaleLinear<string>().domain([0,max/2,max]).range(["#27212C","#B580F4","#CDA1F9"]),max};},[geojson,counts]);
 const schoolList=schools.filter(s=>s.region===selected).slice(0,5);
 return <div className="grid gap-5 lg:grid-cols-[1.4fr_1fr]"><div><svg viewBox="-15 -15 580 510" className="max-h-[510px] w-full" role="img" aria-label={`Répartition estimée par région : ${total-unlocated} élèves localisés, ${unlocated} non localisés`}><title>France métropolitaine, rattachement estimé des établissements</title>{paths.map(p=><path key={p.name} d={p.path} fill={color(counts.get(p.name)??0)} stroke={selected===p.name?"#F3F0F9":"#0E0911"} strokeWidth={selected===p.name?3:1.5} tabIndex={0} role="button" aria-label={`${p.name} : ${counts.get(p.name)??0} élèves`} onFocus={()=>setSelected(p.name)} onMouseEnter={()=>setSelected(p.name)} onClick={()=>setSelected(p.name)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setSelected(p.name);}}}><title>{`${p.name} : ${counts.get(p.name)??0} élèves`}</title></path>)}</svg><div className="mx-auto flex max-w-xs items-center gap-3 text-xs text-[#A8A0B4]"><span>0</span><div className="h-3 flex-1 rounded-full" style={{background:"linear-gradient(to right,#27212C,#B580F4,#CDA1F9)"}}/><span>{max} élèves</span></div></div><div className="space-y-5"><div className="rounded-2xl border border-[#E8A13C] bg-[#3A2820] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#FFB08F]">Non localisés</p><p className="mt-1 font-display text-4xl">{unlocated}<span className="ml-2 font-sans text-sm text-[#CDC8D6]">sur {total} élèves</span></p><p className="mt-2 text-xs text-[#CDC8D6]">Nom absent, non reconnu ou ambigu. Ces élèves restent dans les effectifs.</p></div><div><h3 className="mb-3 text-sm font-bold">Outre-mer</h3><div className="flex flex-wrap gap-2">{drom.map(r=><button key={r} onClick={()=>setSelected(r)} onMouseEnter={()=>setSelected(r)} onFocus={()=>setSelected(r)} className="rounded-full border border-[#332D3D] bg-[#27212C] px-3 py-2 text-xs">{r} · {counts.get(r)??0}</button>)}</div></div><div className="min-h-44 rounded-2xl bg-[#09060C] p-4" aria-live="polite"><h3 className="font-bold">{selected??"Explorer une région"}</h3>{selected?<><p className="mt-2 text-sm text-[#CDA1F9]">{counts.get(selected)??0} élèves · rattachement estimé</p><ul className="mt-3 space-y-2 text-xs text-[#CDC8D6]">{schoolList.map(s=><li key={s.school}>{s.school} · {s.count}</li>)}</ul>{!schoolList.length&&<p className="mt-3 text-xs text-[#A8A0B4]">Aucun établissement rattaché.</p>}<p className="mt-3 text-xs text-[#A8A0B4]">Les 5 établissements les plus représentés.</p></>:<p className="mt-3 text-xs text-[#A8A0B4]">Survolez, touchez ou sélectionnez une région au clavier pour voir ses établissements.</p>}</div></div></div>;
}
