import Link from "next/link";
import { Sparkline } from "./charts";
import { number, type Insight, type funnel } from "@/lib/insights";
export type SearchProps={searchParams:Promise<{apercu?:string;q?:string}>};
export const referenceDate=(preview:boolean)=>preview?"2026-09-10":new Date().toISOString().slice(0,10);
export function Source({name,window}:{name:string;window:string}){return <p className="mt-4 border-t border-[#332D3D] pt-3 text-[11px] text-[#A8A0B4]">Source : <span className="font-mono">{name}</span> · {window}</p>;}
export function PreviewBanner({preview}:{preview:boolean}){return preview?<aside className="mb-6 rounded-2xl border-2 border-[#FFB08F] bg-[#3A2820] px-5 py-4" role="status"><p className="text-sm font-bold text-[#FFB08F]">Aperçu avec des données fictives, rien ici n’est réel</p><p className="mt-1 text-xs text-[#CDC8D6]">Scénario figé au 10 septembre 2026. Les formulaires d’écriture sont désactivés.</p></aside>:null;}
export function Findings({items}:{items:Insight[]}){return <section aria-label="Ce que disent les données" className="mb-6 grid gap-3 lg:grid-cols-2">{items.map((item,i)=><article key={i} className={`rounded-2xl border-l-2 bg-[#1D1822] p-4 ${item.tone==="critique"?"border-[#E14D5E]":item.tone==="alerte"?"border-[#E8A13C]":item.tone==="calme"?"border-[#2FA97C]":"border-[#B580F4]"}`}><p className="text-sm leading-relaxed text-[#F3F0F9]">{item.text}</p><Source name={item.source} window={item.window}/></article>)}</section>;}
export function ChartPanel({title,source,window,caveat,error,children}:{title:string;source:string;window:string;caveat?:string;error?:boolean;children:React.ReactNode}){return <section className="min-w-0 rounded-3xl border border-[#332D3D] bg-[#1D1822] p-5"><h2 className="font-display text-xl">{title}</h2>{caveat&&<p className="mt-2 text-xs text-[#FFB08F]">{caveat}</p>}<div className="mt-5">{error?<p className="empty-chart">La source n’a pas répondu. Impossible de conclure.</p>:children}</div><Source name={source} window={window}/></section>;}
export function PulseTile({label,value,values=[],delta,source,window,tone="calme",detail}:{label:string;value:string;values?:(number|null)[];delta?:string;source:string;window:string;tone?:"calme"|"alerte"|"critique";detail?:string}){return <section className="rounded-2xl border border-[#332D3D] bg-[#1D1822] p-4"><p className="text-sm text-[#CDC8D6]">{label}</p><p className="mt-2 font-display text-4xl">{value}</p><p className={`mt-2 text-xs ${tone==="critique"?"text-[#FFA1AC]":tone==="alerte"?"text-[#F6C86B]":"text-[#8FD8C2]"}`}>{delta??"Comparaison précédente indisponible"}</p>{detail&&<p className="mt-2 text-xs text-[#A8A0B4]">{detail}</p>}<Sparkline values={values} label={`${label}, évolution quotidienne`}/><Source name={source} window={window}/></section>;}
export function Funnel({steps}:{steps:ReturnType<typeof funnel>}){const max=Math.max(...steps.map(s=>s.value),1),worst=Math.max(...steps.map(s=>s.lost));return <div className="overflow-x-auto" role="img" aria-label="Entonnoir des installations, de l’arrivée au compte ajouté"><div className="grid min-w-[510px] grid-cols-5 items-end gap-2">{steps.map((s,i)=><div key={s.label}><p className="mb-2 font-display text-3xl">{s.value}</p><div className="rounded-t-xl p-3 text-[#1A1224]" style={{height:40+150*s.value/max,background:i&&s.lost===worst&&worst>0?"#FF8B95":"#B580F4"}}><p className="text-xs font-bold">{s.label}</p></div><p className="mt-2 min-h-12 text-xs text-[#CDC8D6]">{i?`${s.lost} perdues · ${s.lossPct===null?"taux indisponible":number(s.lossPct)+" %"}`:"Point de départ"}</p></div>)}</div><p className="mt-3 text-xs text-[#A8A0B4]">Corail : plus grande perte en nombre d’installations. Pourcentages calculés depuis la marche précédente.</p></div>;}
export function DetailLink({href,preview}:{href:string;preview:boolean}){return <Link className="mt-4 inline-block text-sm font-semibold text-[#CDA1F9] underline underline-offset-4" href={`${href}${preview?"?apercu=1":""}`}>Voir le détail{preview?" en aperçu":""} →</Link>;}
