import { DenseTable, Metric, PageHeader, ViewPanel } from "@/components/dashboard/analytics-ui";
import { readView } from "@/lib/views";
export const dynamic = "force-dynamic"; export const revalidate = 0;
export default async function MatinPage() {
  const [alertes, pouls, versions, demarrage, fuites, inconnus] = await Promise.all([readView("v_alertes"), readView("v_pouls"), readView("v_versions", { limit: 12 }), readView("v_demarrage", { limit: 12 }), readView("v_demo_fuites", { limit: 12 }), readView("v_evenements_inconnus", { limit: 12 })]);
  const p = pouls.data[0];
  return <><PageHeader title="Le matin" description="Le tableau de bord quotidien. Les alertes montrent ce qui mérite une lecture avant le reste." />
    <ViewPanel title="Alertes des dernières 24 heures" view="v_alertes" error={alertes.error} empty={!alertes.data.length}><DenseTable label="Alertes" rows={alertes.data} columns={[{key:"indicateur",label:"Indicateur",emphasis:true},{key:"valeur",label:"Valeur"},{key:"seuil",label:"Seuil"},{key:"etat",label:"État"}]} /></ViewPanel>
    <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{p ? <><Metric question="Élèves ayant travaillé au moins 3 jours sur 7" value={p.north_star_3j} detail={`${p.north_star_pct}% des actifs sur 7 jours`} view="v_pouls" tone="menthe" /><Metric question="Actifs aujourd’hui" value={p.actifs_aujourdhui} detail={`${p.actifs_7j} sur 7 jours, ${p.actifs_30j} sur 30 jours`} view="v_pouls"/><Metric question="DAU / MAU" value={`${p.dau_mau_pct}%`} detail="Objectif interne : plus de 30 %" view="v_pouls" tone="peche"/><Metric question="Conversion onboarding sur 7 jours" value={`${p.onboarding_pct_7j}%`} detail={`${p.installs_7j} installations, ${p.demos_7j} démos`} view="v_pouls" tone="rose"/></> : <div className="md:col-span-4"><ViewPanel title="Pouls produit" view="v_pouls" error={pouls.error} empty /></div>}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><ViewPanel title="Versions actives sur 30 jours" view="v_versions" error={versions.error} empty={!versions.data.length}><DenseTable label="Versions actives" rows={versions.data} columns={[{key:"app_version",label:"Version",emphasis:true},{key:"platform",label:"Plateforme"},{key:"eleves",label:"Élèves"},{key:"evenements",label:"Événements"},{key:"depuis",label:"Depuis"}]} /></ViewPanel><ViewPanel title="Démarrage à froid sur 14 jours" view="v_demarrage" error={demarrage.error} empty={!demarrage.data.length}><DenseTable label="Démarrage" rows={demarrage.data} columns={[{key:"appareil",label:"Appareil",emphasis:true},{key:"platform",label:"Plateforme"},{key:"lancements",label:"Lancements"},{key:"p50_ms",label:"P50 ms"},{key:"p95_ms",label:"P95 ms"}]} /></ViewPanel></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><ViewPanel title="Fuites de données de démo" view="v_demo_fuites" caveat="Doit rester vide" error={fuites.error} empty={!fuites.data.length}><DenseTable label="Fuites de démo" rows={fuites.data} columns={[{key:"famille",label:"Famille"},{key:"app_version",label:"Version"},{key:"platform",label:"Plateforme"},{key:"n",label:"Événements"}]} /></ViewPanel><ViewPanel title="Événements inconnus" view="v_evenements_inconnus" caveat="Doit rester vide" error={inconnus.error} empty={!inconnus.data.length}><DenseTable label="Événements inconnus" rows={inconnus.data} columns={[{key:"event_name",label:"Événement"},{key:"n",label:"Nombre"},{key:"app_version",label:"Version"},{key:"dernier",label:"Dernier"}]} /></ViewPanel></div></>;
}
