import {PageHeader} from "@/components/dashboard/analytics-ui";
import {ChartPanel,Findings,Funnel,PreviewBanner,PulseTile,DetailLink,referenceDate,type SearchProps} from "@/components/dashboard/story";
import {TimeChart,type ChartRow} from "@/components/dashboard/charts";
import {readView} from "@/lib/views";
import {aiInsights,onboardingInsights,pulseInsights,funnel,inDays,sum,number} from "@/lib/insights";
export const dynamic="force-dynamic";export const revalidate=0;
export default async function Page({searchParams}:SearchProps){const preview=(await searchParams).apercu==="1",end=referenceDate(preview);const [pulse,alerts,onboarding,abandons,ai,ritual,fuites,inconnus]=await Promise.all([readView("v_pouls",{preview}),readView("v_alertes",{preview}),readView("v_onboarding",{preview}),readView("v_onboarding_abandons",{preview}),readView("v_ai_pouls",{preview}),readView("v_gamification",{preview}),readView("v_demo_fuites",{preview}),readView("v_evenements_inconnus",{preview})]);const p=pulse.data[0],week=inDays(ai.data,end,7),before=inDays(ai.data,end,7,7),efforts=inDays(ritual.data,end,7),previousEfforts=inDays(ritual.data,end,7,7);const history:ChartRow[]=Array.from({length:30},(_,i)=>{const label=new Date(Date.parse(end+"T00:00:00Z")-(29-i)*86400000).toISOString().slice(0,10);return {label,actifs:i===29&&p?p.actifs_aujourdhui:null,nouveaux:i===29&&p?p.nouveaux_aujourdhui:null};});
return <><PreviewBanner preview={preview}/><PageHeader title="Le matin" description="Le pouls de LUCID. Ce qui avance, ce qui retient les élèves et ce qui mérite votre attention."/>
<div className="mb-6 rounded-2xl border border-[#332D3D] bg-[#09060C] p-4" role="status" aria-label="Alertes des dernières 24 heures"><h2 className="mb-3 text-sm font-bold">À regarder ce matin</h2>{alerts.error?<p>Les alertes n’ont pas répondu.</p>:!alerts.data.length?<p>Aucune mesure d’alerte disponible.</p>:<div className="flex flex-wrap gap-2">{[...alerts.data].sort((a,b)=>Number(b.etat==="à regarder")-Number(a.etat==="à regarder")).map((a,i)=><span key={i} className={`rounded-xl border px-3 py-2 text-xs ${a.etat==="à regarder"?"border-[#E8A13C] bg-[#3A2820] text-[#FFB08F]":a.etat==="calme"?"border-[#173230] bg-[#173230] text-[#8FD8C2]":"border-[#332D3D] text-[#A8A0B4]"}`}><strong>{a.indicateur}</strong> : {a.valeur} · seuil {a.seuil}<span className="ml-2">{a.etat}</span></span>)}</div>}<p className="mt-3 text-[11px] text-[#A8A0B4]">Source : v_alertes · 24 heures</p></div>
<Findings items={[...pulseInsights(p),onboardingInsights(onboarding.data,abandons.data)[0],...aiInsights(ai.data,p,end)]}/>
<div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><PulseTile label="Actifs aujourd’hui" value={p?String(p.actifs_aujourdhui):"Non mesuré"} detail={p?`${p.actifs_7j} sur 7 jours · ${p.actifs_30j} sur 30 jours`:undefined} source="v_pouls" window="Aujourd’hui"/><PulseTile label="L’étoile polaire" value={p?`${number(p.north_star_pct)} %`:"Non mesuré"} detail="Actifs ayant travaillé au moins 3 jours sur 7" source="v_pouls" window="7 jours"/><PulseTile label="Coût IA sur 7 jours" value={week.length?`${number(sum(week,"cout_usd_estime"),4)} $`:"Non mesuré"} values={ai.data.sort((a,b)=>a.jour.localeCompare(b.jour)).map(r=>r.cout_usd_estime)} delta={week.length===7&&before.length===7?`${number(sum(week,"cout_usd_estime")-sum(before,"cout_usd_estime"),4)} $ vs 7 jours précédents`:undefined} source="v_ai_pouls" window="7 jours · courbe sur 30 jours"/><PulseTile label="Journées validées" value={efforts.length?String(sum(efforts,"journees_validees")):"Non mesuré"} values={[...ritual.data].sort((a,b)=>a.jour.localeCompare(b.jour)).map(r=>r.journees_validees)} delta={efforts.length===7&&previousEfforts.length===7?`${sum(efforts,"journees_validees")-sum(previousEfforts,"journees_validees")} vs 7 jours précédents`:undefined} source="v_gamification" window="7 jours · courbe sur 30 jours, démo et dev inclus" tone={sum(efforts,"journees_validees")<sum(previousEfforts,"journees_validees")?"alerte":"calme"}/></div>
<div className="grid items-start gap-5 xl:grid-cols-2"><ChartPanel title="Actifs et nouveaux sur 30 jours" source="v_pouls" window="Instantané actuel" error={pulse.error} caveat="Historique quotidien absent du socle : seul aujourd’hui est mesuré. Les 29 jours précédents sont laissés vides."><TimeChart title="Actifs et nouveaux, historique manquant" rows={history} series={[{key:"actifs",name:"Actifs"},{key:"nouveaux",name:"Nouveaux"}]} end={end}/><DetailLink href="/dashboard/retention" preview={preview}/></ChartPanel>
<ChartPanel title="La marche qui retient les installations" source="v_onboarding" window="30 jours, cohortes d’arrivée" error={onboarding.error}>{onboarding.data.length?<Funnel steps={funnel(onboarding.data)}/>:<p>Aucune installation mesurée.</p>}<DetailLink href="/dashboard/entonnoir" preview={preview}/></ChartPanel>
<ChartPanel title="L’effort au quotidien" source="v_gamification" window="30 jours" caveat="Démo et dev inclus" error={ritual.error}><TimeChart title="Journées validées" rows={ritual.data.map(r=>({label:r.jour,journees:r.journees_validees}))} series={[{key:"journees",name:"Journées validées"}]} average end={end}/><DetailLink href="/dashboard/rituel" preview={preview}/></ChartPanel>
<ChartPanel title="La santé du moteur IA" source="v_ai_pouls" window="7 jours, courbe sur 30 jours" error={ai.error}><p className="mb-3 text-sm">{aiInsights(ai.data,p,end)[1].text}</p><TimeChart title="Requêtes et pannes IA" rows={ai.data.map(r=>({label:r.jour,requetes:r.requetes,pannes:r.echecs}))} series={[{key:"requetes",name:"Requêtes"},{key:"pannes",name:"Pannes"}]} end={end}/><DetailLink href="/dashboard/ia" preview={preview}/></ChartPanel></div>
<div className="mt-5 grid gap-4 md:grid-cols-2">{[{r:fuites,source:"v_demo_fuites",title:"Fuites de démo",window:"30 jours"},{r:inconnus,source:"v_evenements_inconnus",title:"Événements inconnus",window:"7 jours"}].map(({r,source,title,window})=><div key={source} className={`rounded-2xl border p-5 ${r.error?"border-[#332D3D]":r.data.length?"border-[#E14D5E] bg-[#38222B] text-[#FFA1AC]":"border-[#2FA97C] bg-[#173230] text-[#8FD8C2]"}`}><h2 className="font-bold">{title}</h2><p className="mt-2">{r.error?"Vérification impossible : la vue n’a pas répondu.":`${r.data.reduce((total,row)=>total+row.n,0)} événements · ${r.data.length} lignes. ${r.data.length?"À corriger : cette vue doit rester vide.":"Tout est calme, la vue est vide."}`}</p><p className="mt-3 text-xs">Source : {source} · {window}</p></div>)}</div></>;}
