import {PageHeader} from "@/components/dashboard/analytics-ui";
import {ChartPanel,Findings,Funnel,PreviewBanner,PulseTile,DetailLink,referenceDate,type SearchProps} from "@/components/dashboard/story";
import {TimeChart,Donut,type ChartRow} from "@/components/dashboard/charts";
import {readView} from "@/lib/views";
import {aiInsights,onboardingInsights,pulseInsights,funnel,inDays,sum,number} from "@/lib/insights";
export const dynamic="force-dynamic";export const revalidate=0;
export default async function Page({searchParams}:SearchProps){const preview=(await searchParams).apercu==="1",end=referenceDate(preview);const [pulse,alerts,onboarding,abandons,ai,ritual,fuites,inconnus,serie,parts]=await Promise.all([readView("v_pouls",{preview}),readView("v_alertes",{preview}),readView("v_onboarding",{preview}),readView("v_onboarding_abandons",{preview}),readView("v_ai_pouls",{preview}),readView("v_gamification",{preview}),readView("v_demo_fuites",{preview}),readView("v_evenements_inconnus",{preview}),readView("v_actifs_quotidiens",{preview}),readView("v_repartitions",{preview})]);const p=pulse.data[0],week=inDays(ai.data,end,7),before=inDays(ai.data,end,7,7),efforts=inDays(ritual.data,end,7),previousEfforts=inDays(ritual.data,end,7,7);const jours=[...serie.data].sort((a,b)=>a.jour.localeCompare(b.jour)),history:ChartRow[]=jours.map(r=>({label:r.jour.slice(0,10),actifs:r.actifs,nouveaux:r.nouveaux,ia:r.actifs_ia})),today=jours[jours.length-1],weekAgo=jours[jours.length-8],delta7=today&&weekAgo?today.actifs_7j-weekAgo.actifs_7j:null,famille=(f:string)=>parts.data.filter(r=>r.famille===f).map(r=>({label:r.valeur,value:r.eleves}));
return <><PreviewBanner preview={preview}/><PageHeader title="Le matin" description="Le pouls de LUCID. Ce qui avance, ce qui retient les élèves et ce qui mérite votre attention."/>
<div className="mb-6 rounded-2xl border border-[#332D3D] bg-[#09060C] p-4" role="status" aria-label="Alertes des dernières 24 heures"><h2 className="mb-3 text-sm font-bold">À regarder ce matin</h2>{alerts.error?<p>Les alertes n’ont pas répondu.</p>:!alerts.data.length?<p>Aucune mesure d’alerte disponible.</p>:<><ul className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap">{[...alerts.data].sort((a,b)=>Number(b.etat==="à regarder")-Number(a.etat==="à regarder")).map((a,i)=><li key={i} className={`flex min-w-0 items-center gap-2 rounded-xl border px-3 py-2 text-xs ${a.etat==="à regarder"?"border-[#E8A13C]/60 bg-[#3A2820] text-[#FFB08F]":a.etat==="calme"?"border-[#173230] bg-[#173230] text-[#8FD8C2]":"border-[#332D3D] text-[#A8A0B4]"}`}><span className={`size-2 shrink-0 rounded-full ${a.etat==="à regarder"?"bg-[#E8A13C]":a.etat==="calme"?"bg-[#2FA97C]":"bg-[#6E6680]"}`} aria-hidden="true"/><span className="min-w-0 flex-1 truncate">{a.indicateur}</span><strong className="tabular-nums">{a.valeur}</strong>{Number(a.seuil)>=0&&<span className="hidden text-[10px] opacity-70 sm:inline">/ {a.seuil}</span>}</li>)}</ul><p className="mt-2 text-[11px] text-[#A8A0B4]">Ambre : au-dessus du seuil (valeur / seuil). Vert : calme. Gris : pour mémoire.</p></>}<p className="mt-3 text-[11px] text-[#A8A0B4]">Source : v_alertes · 24 heures</p></div>
<Findings items={[...pulseInsights(p),onboardingInsights(onboarding.data,abandons.data)[0],...aiInsights(ai.data,p,end)]}/>
<div className="mb-4 grid grid-cols-2 gap-3 sm:gap-4 xl:grid-cols-4"><PulseTile label="Actifs aujourd’hui" value={p?String(p.actifs_aujourdhui):"Non mesuré"} detail={p?`${p.actifs_7j} sur 7 jours · ${p.actifs_30j} sur 30 jours`:undefined} values={jours.map(r=>r.actifs)} delta={delta7!==null?`${delta7>=0?"+":""}${delta7} actifs sur 7 jours vs la semaine précédente`:undefined} tone={delta7!==null&&delta7<0?"alerte":"calme"} source="v_pouls / v_actifs_quotidiens" window="Aujourd’hui · courbe sur 30 jours"/><PulseTile label="L’étoile polaire" value={p?`${number(p.north_star_pct)} %`:"Non mesuré"} detail="Actifs ayant travaillé au moins 3 jours sur 7" source="v_pouls" window="7 jours"/><PulseTile label="Coût IA sur 7 jours" value={week.length?`${number(sum(week,"cout_usd_estime"),4)} $`:"Non mesuré"} values={ai.data.sort((a,b)=>a.jour.localeCompare(b.jour)).map(r=>r.cout_usd_estime)} delta={week.length===7&&before.length===7?`${number(sum(week,"cout_usd_estime")-sum(before,"cout_usd_estime"),4)} $ vs 7 jours précédents`:undefined} source="v_ai_pouls" window="7 jours · courbe sur 30 jours"/><PulseTile label="Journées validées" value={efforts.length?String(sum(efforts,"journees_validees")):"Non mesuré"} values={[...ritual.data].sort((a,b)=>a.jour.localeCompare(b.jour)).map(r=>r.journees_validees)} delta={efforts.length===7&&previousEfforts.length===7?`${sum(efforts,"journees_validees")-sum(previousEfforts,"journees_validees")} vs 7 jours précédents`:undefined} source="v_gamification" window="7 jours · courbe sur 30 jours, démo et dev inclus" tone={sum(efforts,"journees_validees")<sum(previousEfforts,"journees_validees")?"alerte":"calme"}/></div>
<div className="mb-6 grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-4">{p&&[{label:"Nouveaux sur 7 jours",value:String(p.nouveaux_7j),detail:`${p.nouveaux_aujourdhui} aujourd’hui`},{label:"Installations sur 7 jours",value:String(p.installs_7j),detail:`${p.demos_7j} sont passées par la découverte`},{label:"Comptes ajoutés",value:`${number(p.onboarding_pct_7j)} %`,detail:"des installations de la semaine",tone:p.onboarding_pct_7j>=50?"calme":"alerte"},{label:"Ont utilisé l’IA",value:`${number(p.activation_ia_pct)} %`,detail:"des actifs sur 7 jours"},{label:"Sessions sur 7 jours",value:number(p.sessions_7j),detail:p.actifs_7j?`${number(p.sessions_7j/p.actifs_7j)} par actif`:undefined},{label:"Écrans par jour actif",value:number(p.ecrans_par_jour_actif),detail:"profondeur d’une visite"},{label:"Échecs sur 24 h",value:number(p.echecs_24h),detail:"connexions, synchros, IA",tone:p.echecs_24h>48?"alerte":"calme"},{label:"Erreurs journalisées sur 24 h",value:number(p.erreurs_24h),detail:"app_error, toutes causes",tone:p.erreurs_24h>48?"alerte":"calme"}].map(t=><PulseTile key={t.label} compact label={t.label} value={t.value} detail={t.detail} tone={(t.tone as "calme"|"alerte"|undefined)??"calme"} source="v_pouls" window="7 jours"/>)}</div>
<div className="mb-5 grid gap-4 sm:gap-5 md:grid-cols-3"><ChartPanel title="Quel niveau ?" source="v_repartitions" window="30 jours" error={parts.error}><Donut title="Niveau des élèves actifs" rows={famille("niveau")} unit="élèves"/></ChartPanel><ChartPanel title="Quel ENT ?" source="v_repartitions" window="30 jours" error={parts.error}><Donut title="Service scolaire des élèves actifs" rows={famille("service")} unit="élèves"/></ChartPanel><ChartPanel title="Quel appareil ?" source="v_repartitions" window="30 jours" error={parts.error}><Donut title="Plateforme des élèves actifs" rows={famille("plateforme")} unit="élèves"/></ChartPanel></div>
<div className="grid items-start gap-4 sm:gap-5 xl:grid-cols-2"><ChartPanel title="Actifs et nouveaux sur 30 jours" source="v_actifs_quotidiens" window="30 jours, jours de Paris" error={serie.error} caveat="Élèves avec profil, démo exclue. Un nouveau est compté le jour de sa première activité."><TimeChart title="Actifs, nouveaux et actifs IA par jour" rows={history} series={[{key:"actifs",name:"Actifs"},{key:"nouveaux",name:"Nouveaux"},{key:"ia",name:"Ont utilisé l’IA"}]} average end={end}/><DetailLink href="/dashboard/retention" preview={preview}/></ChartPanel>
<ChartPanel title="La marche qui retient les installations" source="v_onboarding" window="30 jours, cohortes d’arrivée" error={onboarding.error}>{onboarding.data.length?<Funnel steps={funnel(onboarding.data)}/>:<p>Aucune installation mesurée.</p>}<DetailLink href="/dashboard/entonnoir" preview={preview}/></ChartPanel>
<ChartPanel title="L’effort au quotidien" source="v_gamification" window="30 jours" caveat="Démo et dev inclus" error={ritual.error}><TimeChart title="Journées validées" rows={ritual.data.map(r=>({label:r.jour,journees:r.journees_validees}))} series={[{key:"journees",name:"Journées validées"}]} average end={end}/><DetailLink href="/dashboard/rituel" preview={preview}/></ChartPanel>
<ChartPanel title="La santé du moteur IA" source="v_ai_pouls" window="7 jours, courbe sur 30 jours" error={ai.error}><p className="mb-3 text-sm">{aiInsights(ai.data,p,end)[1].text}</p><TimeChart title="Requêtes et pannes IA" rows={ai.data.map(r=>({label:r.jour,requetes:r.requetes,pannes:r.echecs}))} series={[{key:"requetes",name:"Requêtes"},{key:"pannes",name:"Pannes"}]} end={end}/><DetailLink href="/dashboard/ia" preview={preview}/></ChartPanel></div>
<div className="mt-4 grid gap-4 sm:mt-5 md:grid-cols-2">{[{r:fuites,source:"v_demo_fuites",title:"Fuites de démo",window:"30 jours"},{r:inconnus,source:"v_evenements_inconnus",title:"Événements inconnus",window:"7 jours"}].map(({r,source,title,window})=><div key={source} className={`rounded-2xl border p-5 ${r.error?"border-[#332D3D]":r.data.length?"border-[#E14D5E] bg-[#38222B] text-[#FFA1AC]":"border-[#2FA97C] bg-[#173230] text-[#8FD8C2]"}`}><h2 className="font-bold">{title}</h2><p className="mt-2">{r.error?"Vérification impossible : la vue n’a pas répondu.":`${r.data.reduce((total,row)=>total+row.n,0)} événements · ${r.data.length} lignes. ${r.data.length?"À corriger : cette vue doit rester vide.":"Tout est calme, la vue est vide."}`}</p><p className="mt-3 text-xs">Source : {source} · {window}</p></div>)}</div></>;}
