import { pupilInsights } from "@/lib/insights/pages";
import Link from "next/link";
import {notFound} from "next/navigation";
import {updateUsageLimits} from "@/app/actions/admin";
import {PageHeader,DenseTable} from "@/components/dashboard/analytics-ui";
import {ChartPanel,Findings,PreviewBanner,referenceDate,type SearchProps} from "@/components/dashboard/story";
import {TimeChart} from "@/components/dashboard/charts";
import {readView} from "@/lib/views";
export const dynamic="force-dynamic";export const revalidate=0;
export default async function Page({params,searchParams}:SearchProps&{params:Promise<{id:string}>}){const preview=(await searchParams).apercu==="1",id=(await params).id;const [profile,xp,efforts,badges,friends]=await Promise.all([readView("profile_detail",{preview,profileId:id}),readView("daily_xp",{preview,profileId:id,order:"date",limit:30}),readView("gamification_efforts",{preview,profileId:id,order:"day_key",limit:30}),readView("user_badges",{preview,profileId:id}),readView("friendships",{preview,profileId:id})]);const p=profile.data[0];if(!p&&!profile.error)notFound();return <><PreviewBanner preview={preview}/><Link href={`/dashboard/eleves${preview?"?apercu=1":""}`} className="text-sm text-[#CDA1F9]">Retour aux élèves</Link><PageHeader title={p?.full_name||"Élève"} description={`${p?.school_name||"Établissement non renseigné"} · ${p?.class_name||"Classe non renseignée"}`}/><Findings items={pupilInsights(xp,profile,p,badges,friends,id)}/><div className="grid gap-5 xl:grid-cols-2"><ChartPanel title="L’effort dans le temps" source="daily_xp" window="30 derniers jours renseignés" error={xp.error}><TimeChart title="XP quotidienne" rows={xp.data.map(r=>({label:r.date,xp:r.amount}))} series={[{key:"xp",name:"XP"}]} end={referenceDate(preview)}/></ChartPanel><ChartPanel title="Les derniers efforts" source="gamification_efforts" window="30 derniers efforts" error={efforts.error}><DenseTable label="Efforts de l’élève" rows={efforts.data} columns={[{key:"day_key",label:"Jour"},{key:"kind",label:"Effort"},{key:"xp",label:"XP"}]}/></ChartPanel><ChartPanel title="Quotas IA" source="profiles.usage_limits" window="État actuel" error={profile.error}><fieldset disabled={preview||profile.error}><form action={updateUsageLimits}><input type="hidden" name="profile_id" value={id}/><input type="hidden" name="preview" value={preview?"1":"0"}/><label htmlFor="limits" className="text-sm">Quotas au format JSON</label><textarea id="limits" name="usage_limits" defaultValue={JSON.stringify(p?.usage_limits??{},null,2)} className="mt-2 min-h-36 w-full rounded-2xl border border-[#332D3D] bg-[#09060C] p-3 font-mono text-xs"/><button className="control mt-3">Enregistrer les quotas</button></form></fieldset></ChartPanel></div></>;}
