"use server";

import { revalidatePath } from "next/cache";
import { requireDashboardSession } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase-admin";

function fail(error: unknown) { console.error("Écriture tableau de bord impossible", error); throw new Error("L’enregistrement a échoué."); }

export async function updateUsageLimits(formData: FormData) { await requireDashboardSession(); if(formData.get("preview")==="1") throw new Error("Les écritures sont désactivées en aperçu."); const id=String(formData.get("profile_id")); const raw=String(formData.get("usage_limits")||"{}"); try { const usage_limits=JSON.parse(raw); const {error}=await supabaseAdmin.from("profiles").update({usage_limits}).eq("id",id); if(error) throw error; revalidatePath(`/dashboard/eleves/${id}`); } catch(error){fail(error);} }
export async function saveConfig(formData: FormData) { await requireDashboardSession(); if(formData.get("preview")==="1") throw new Error("Les écritures sont désactivées en aperçu."); const key=String(formData.get("key")); const value=String(formData.get("value")); const sensitive=key==="maintenance_mode"||key==="ai_flags"&&value.includes("kill_switch"); const first=String(formData.get("confirmation_one")); const second=String(formData.get("confirmation_two")); if(sensitive && (first!=="CONFIRMER"||second!=="CONFIRMER")) throw new Error("Double confirmation requise."); const {error}=await supabaseAdmin.from("app_config").update({value}).eq("key",key); if(error) fail(error); console.info("Configuration LUCID modifiée",{key,at:new Date().toISOString(),old_value:String(formData.get("old_value")),new_value:value}); revalidatePath("/dashboard/configuration"); }
export async function saveBanner(formData: FormData) { await requireDashboardSession(); if(formData.get("preview")==="1") throw new Error("Les écritures sont désactivées en aperçu."); const id=String(formData.get("id")||""); const payload={title:String(formData.get("title")||""),body:String(formData.get("body")||""),active:formData.get("active")==="on"}; const result=id ? await supabaseAdmin.from("app_banners").update(payload).eq("id",id) : await supabaseAdmin.from("app_banners").insert(payload); if(result.error) fail(result.error); revalidatePath("/dashboard/configuration"); }
export async function savePost(formData: FormData) { await requireDashboardSession(); if(formData.get("preview")==="1") throw new Error("Les écritures sont désactivées en aperçu."); const options=JSON.parse(String(formData.get("options")||"[]")); const audience=JSON.parse(String(formData.get("audience")||"{}")); const payload={kind:String(formData.get("kind")),status:String(formData.get("status")),title:String(formData.get("title")),body:String(formData.get("body")),author_name:String(formData.get("author_name")||"L’équipe LUCID"),options,multi_choice:formData.get("multi_choice")==="on",show_results:formData.get("show_results")==="on",allow_reply:formData.get("allow_reply")==="on",audience,pinned:formData.get("pinned")==="on",publish_at:String(formData.get("publish_at")||"")||null,expires_at:String(formData.get("expires_at")||"")||null,cta_label:String(formData.get("cta_label")||"")||null,cta_url:String(formData.get("cta_url")||"")||null}; if(payload.status==="published"){const count=await supabaseAdmin.rpc("lucid_admin_audience_count",{p_audience:audience});if(count.error)fail(count.error);console.info("Audience courrier vérifiée",{audience,count:count.data});} const {error}=await supabaseAdmin.from("lucid_posts").insert(payload); if(error) fail(error); revalidatePath("/dashboard/courrier"); }
export async function replyToPost(formData: FormData) { await requireDashboardSession(); if(formData.get("preview")==="1") throw new Error("Les écritures sont désactivées en aperçu."); const {error}=await supabaseAdmin.from("lucid_post_replies").insert({post_id:String(formData.get("post_id")),profile_id:String(formData.get("profile_id")),body:String(formData.get("body")),from_staff:true}); if(error) fail(error); revalidatePath("/dashboard/courrier"); }
export async function changeStaff(formData: FormData) { await requireDashboardSession(); if(formData.get("preview")==="1") throw new Error("Les écritures sont désactivées en aperçu."); const id=String(formData.get("profile_id")); const remove=formData.get("remove")==="true"; const result=remove?await supabaseAdmin.from("lucid_staff").delete().eq("profile_id",id):await supabaseAdmin.from("lucid_staff").insert({profile_id:id,label:String(formData.get("label")||"Équipe LUCID")}); if(result.error) fail(result.error); revalidatePath("/dashboard/courrier"); }
