"use server";

import { revalidatePath } from "next/cache";
import { requireDashboardSession } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabase-admin";

function fail(error: unknown) { console.error("Écriture tableau de bord impossible", error); throw new Error("L’enregistrement a échoué."); }

export async function updateUsageLimits(formData: FormData) { await requireDashboardSession(); if(formData.get("preview")==="1") throw new Error("Les écritures sont désactivées en aperçu."); const id=String(formData.get("profile_id")); const raw=String(formData.get("usage_limits")||"{}"); try { const usage_limits=JSON.parse(raw); const {error}=await supabaseAdmin.from("profiles").update({usage_limits}).eq("id",id); if(error) throw error; revalidatePath(`/dashboard/eleves/${id}`); } catch(error){fail(error);} }
export async function saveConfig(formData: FormData) { await requireDashboardSession(); if(formData.get("preview")==="1") throw new Error("Les écritures sont désactivées en aperçu."); const key=String(formData.get("key")); const value=String(formData.get("value")); const sensitive=key==="maintenance_mode"||key==="ai_flags"&&value.includes("kill_switch"); const first=String(formData.get("confirmation_one")); const second=String(formData.get("confirmation_two")); if(sensitive && (first!=="CONFIRMER"||second!=="CONFIRMER")) throw new Error("Double confirmation requise."); const {error}=await supabaseAdmin.from("app_config").update({value}).eq("key",key); if(error) fail(error); console.info("Configuration LUCID modifiée",{key,at:new Date().toISOString(),old_value:String(formData.get("old_value")),new_value:value}); revalidatePath("/dashboard/configuration"); }
export async function saveBanner(formData: FormData) { await requireDashboardSession(); if(formData.get("preview")==="1") throw new Error("Les écritures sont désactivées en aperçu."); const id=String(formData.get("id")||""); const style=String(formData.get("style_type")||"info"); const active=formData.get("active")==="on"; const message=String(formData.get("message")||"").trim(); if(!id&&!message) throw new Error("Un bandeau a besoin d’un message."); const result=id ? await supabaseAdmin.from("app_banners").update({active}).eq("id",id) : await supabaseAdmin.from("app_banners").insert({message,active,style_type:["info","warning","success"].includes(style)?style:"info",link_url:String(formData.get("link_url")||"").trim()||null,link_text:String(formData.get("link_text")||"").trim()||null}); if(result.error) fail(result.error); revalidatePath("/dashboard/configuration"); }
export async function changeStaff(formData: FormData) { await requireDashboardSession(); if(formData.get("preview")==="1") throw new Error("Les écritures sont désactivées en aperçu."); const id=String(formData.get("profile_id")); const remove=formData.get("remove")==="true"; const result=remove?await supabaseAdmin.from("lucid_staff").delete().eq("profile_id",id):await supabaseAdmin.from("lucid_staff").insert({profile_id:id,label:String(formData.get("label")||"Équipe LUCID")}); if(result.error) fail(result.error); revalidatePath("/dashboard/courrier"); }
